### ISSUE TITLE
Inconsistencies with `kw drm`

### ISSUE THREAD

**Issue by MarceloSpessoto** [kworkflow/kworkflow#1002]
**Description:**
The `kw drm` command could be improved. 
First of all, when running `kw drm` without options, nothing is displayed. It could show the list of available options, to provide a more user friendly experience and keep consistency with commands such as `kw remote` and `kw pomodoro`.
Another problem is the use of load/unload modules features.  It is said that we can load modules with (-lm|--load-module)=\<module\> and unload with (-um|--unload-module)=\<module\>. However, only the `--` commands are functional, `-lm` and `-um` are broken and not implemented at all. I think it would be better to remove `-lm` and `-rm` from the documentation and stick only with the long commands.
Finally, the use `--load-module`/`--unload-module` could display to the user a success message, indicating the module was effectively loaded/unloaded.

**Type:**
UX

**Why:**
These improvementes would make user experience smoother and more consistent.
Also, the documentation of `-lm`/`-rm` commands is misleading and should be treated.

**Comment by rodrigosiqueira** [comment]
Yeah... this option is ancient and requires a lot of improvements, such as using the new code pattern described at https://kworkflow.org/content/project_structure.html#components . We can also make this feature way more powerful by exploring many options from the sysfs and edid tools. This is a very good first issue to learn more about kw and DRM debug tools.

**Comment by Vighnesh-Patidar** [comment]
Please let me work on this issue.

**Comment by fernando38954** [comment]
I'll try to work on this issue.
