### ISSUE TITLE
kw pomodoro --list does not exist

### ISSUE THREAD

**Issue by jppaulo06** [kworkflow/kworkflow#1006]
**Description:**

It is stated in the [KW pomodoro documentation](https://kworkflow.org/tutorials/pomodoro-report.html) that `kw p --list` or `kw p -l` prints the Pomodoro time left. However, this option does not exist, and probably, now `kw p --check-timer` is responsible for that.

**Expected behavior:**

The documentation is expected to provide information about the correct command.

**Screenshots:**

Screenshot from kw docs:
![image](https://github.com/kworkflow/kworkflow/assets/102490154/87be0320-52c5-42d9-8d52-592fa8ae7c7e)

**Comment by rodrigosiqueira** [comment]
@jppaulo06 @davidbtadokoro, could you make the PR that addresses this issue?
