### ISSUE TITLE
kw pomodoro -g does not exist

### ISSUE THREAD

**Issue by jppaulo06** [kworkflow/kworkflow#1007]
**Description:**

It is stated in the [KW pomodoro documentation](https://kworkflow.org/tutorials/pomodoro-report.html) that `kw p -g` prints Pomodoro tags. However, this option does not exist, and `kw p -s` is responsible for that.

**Expected behavior:**

The documentation is expected to provide information about the correct command.

**Screenshots:**

![image](https://github.com/kworkflow/kworkflow/assets/102490154/a0f4b7ca-71d8-4ca0-bdaa-c0d3d3ebed58)

**Comment by rodrigosiqueira** [comment]
Yeah, a long time ago, @davidbtadokoro updated this feature, and it looks like we forgot to update part of the documentation.

@davidbtadokoro @jppaulo06 could you make the PR for this?
