### ISSUE TITLE
Option `--restart` to pomodoro

### ISSUE THREAD

**Issue by jppaulo06** [kworkflow/kworkflow#1009]
**Description:**

Sometimes, I want to restart a pomodoro session that has just ended, with the exact same configuration. So, I think it would be a good enhancement to have a `--restart` (or `-r`) flag in `kw pomodoro` command.

**Type:**

UX

**Why:**

I think it would enhance user experience.

 Currently, to start a pomodoro session, you would first write:
``` 
kw pomodoro -t 30m -g "New tag" -d "I know how to reproduce the bug! I'm going to try THIS WORKAROUND to see if it fixes the issue"
```
And, for every new "clone session", you would need to write something like
```
kw pomodoro -t 30m -g 1 -d "I know how to reproduce the bug! I'm going to try THIS WORKAROUND to see if it fixes the issue"
```
The good thing is that you don't need to repeat the tag. However, you do need to repeat the time and the description, which is a bit tedious.

With this proposed enhancement (`--repeat`), every new "clone session" would be created with just
```
kw pomodoro --repeat
```

**Comment by Vighnesh-Patidar** [comment]
I would like to work on this

**Comment by th-duvanel** [comment]
I can work on this.
