### ISSUE TITLE
Standardize parser functions

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#103]
Each specific kw command has a tiny parser (usually, it starts with execute_*). Probably it is a good idea to create a pattern for this in the code, I'm thinking about using "parser_command" as a default name.

**Comment by joaoseckler** [comment]
This issue is partially addressed by PR #390, which implements a wrapper around getopt in kwlib.sh. To complete this issue, we should use this wrapper in all modules of kw and document the usage and best practices.
