### ISSUE TITLE
Add context to kw explore results

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#1052]
**Description:**

Expand `kw explore` to show some extra context after matching a string, and I believe that we have a perfect tool for that: `batcat`. After the normal exploration matches a file and its lines, we can show X lines above and after the match and show it to the user with the below command:

```
batcat -P  --line-range <START>:<END> <FILE>
```

e.g.:

```sh
batcat -P  --line-range 30:+10 Makefile
```

**Type:**

Feature improvement

**Why:**

Sometimes, when searching for a code, it has multiple matches in the code, and it helps to see the context. Maybe we can have something like:

```sh
kw e -H --show-context dc_stream_state
```

**Comment by iamtvk** [comment]
I want to work on this, I am new to this codebase, so any input is much appreciated.

**Comment by sahil-sagwekar2652** [comment]
@rodrigosiqueira I would like to know your thoughts on this PR https://github.com/kworkflow/kworkflow/pull/1058
