### ISSUE TITLE
Order of arguments in assert_equals_helper is the oposite of what is decalred

### ISSUE THREAD

**Issue by auyer** [kworkflow/kworkflow#1091]
Both in docs and in its usage in evey test file of kworkflow, the `assert_equals_helper` arguments are defined to be ` "($LINENO)" "$output" "$expected_output"`.
But in reality, the function interprets it as ` "($LINENO)" "$expected_output" "$output"`

I stumbled upon this while testing a different change, and getting very confused by the output of the test I was adding.

**How to Reproduce:**

[Steps to reproduce the behavior:
1. Change a expected value in any test
2. Run `./run_tests.sh test <file>`
3. Check what gets printed out

**Expected behavior:**

```bash
./run_tests.sh test mail                               
...
test_mail_parser
ASSERT: line 324: Set to flag
  Expected Result: intentional-error@demo.com
    Actual Result: some@mail.com
```

**Actual behavior:**

```bash
./run_tests.sh test mail                               
...
ASSERT: line 324: Set to flag
  Expected Result: some@mail.com
    Actual Result: intentional-error@demo.com
```

**Comment by davidbtadokoro** [comment]
Hi @auyer, nice catch! Actually, what is wrong is the documentation and some test files (the old ones) that use the wrong order. We've noticed this mistake a while, and are now doing the correct way.

To sum up, IMHO, the correct approach is to fix de documentation and update the wrong order in the test files that use `output` as arg 3 and `expected` as arg 4.
