### ISSUE TITLE
Improve --conn-available to share more helpful information about the connector usage

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#1096]
**Description:**

`kw drm` has the `--conn-available` option, which lists all the connectors available in the dGPU/APU. For example, if your GPU has three DPs and one HDMI you should see something like this:
```
[local] Card0 supports:
 DP
 DP
 DP
 HDMI
```
To make this information more meaningful, we should add a mark to tell the user which connector it is in use. From the above example, suppose that I have one display connected to the second DP and another one to the HDMI; we should have an output that looks like this:

```
[local] Card0 supports:
 DP
 DP *
 DP
 HDMI *
```

This information can be achieved by using the command:

```
cat /sys/class/drm/card0-<CONNECTOR-ID>/enabled
```

**Comment by otavioolsilva** [comment]
Hi! I think I can work on this issue.
