### ISSUE TITLE
Create environments managed by kw

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#114]
When we work with Linux Kernel, sometimes we want to manager multiple ways to build the kernel; for example, we want to build a kernel version for x86 and arm. It could be nice if we have a mechanism that isolates the binaries and allows us to switch between them, something like this:
```bash
cd kernel_dir/
kw env create RASP_BUILD
kw env create X86_BUILD
kw env use RASP_BUILD
kw b # Compile and keep the object/binaries in one place
kw env use X86_BUILD
kw b # Compile and keep x86 stuff in another place
kw env clean RASP_BUILD # Clean the build
kw env destroy RASP_BUILD # Remove the environment previously created
```
Finally, it could be awesome if we can display the env info in bash line. Something like this:

```bash
[0,0][21:27:56]siqueira@atma ~/Documents/Repositories/kworkflow/kw [master][kw:X86_BUILD]
$
```

**Comment by rodrigosiqueira** [comment]
An easier way to implement this feature relies on `make O=PATH` option that allows us to point to a specific directory, however, for using this feature you have to pay extra attention to the following note in the Linux kernel documentation [1]:

Please note: If the `O=output/dir` option is used, then it must be
   used for all invocations of make.

https://www.kernel.org/doc/Documentation/admin-guide/README.rst

**Comment by joaoseckler** [comment]
Possible user interface for this feature:

**Comment by rodrigosiqueira** [comment]
@melissawen, what do you think about this interface?

@joaoseckler also add the sidequests in your previous comment.

**Comment by melissawen** [comment]
> @melissawen, what do you think about this interface?

Lgtm. But for --use I would prefer --run. I would also like to have an option to run a single kw command from one env on another. I mean, do not completely switch my current environment when I just need to run one command, is it possible?

Btw, --clean is not clear to me and the name may lead misconceptions. If it will work as make clean, just use 'make clean' in the correct env is enough to me (no needs of a wrap)
> 
> @joaoseckler also add the sidequests in your previous comment.

**Comment by joaoseckler** [comment]
> > @melissawen, what do you think about this interface?
> 
> Lgtm. But instead of --use I would prefer --run. 

Wouldn't --run convey the idea that we are executing something? Rather than just changing the current environment. Python's virtualenv uses activate and deactivate, and rvm uses the ideia of "set". What do you think of these?

> I would also like to have an option to run a single kw command from one env on another. I mean, do not completely switch my current environment when I just need to run one command, is it possible?

Nice

> 
> Btw, --clean is not clear to me and the name may lead misconceptions. If it will work as make clean, just use 'make clean' in the correct env is enough to me (no needs of a wrap)

Nice 
> 
> > @joaoseckler also add the sidequests in your previous comment.

**Comment by joaoseckler** [comment]
> > I would also like to have an option to run a single kw command from one env on another. I mean, do not completely switch my current environment when I just need to run one command, is it possible?

@melissawen would you like to execute arbitrary commands or only kw commands?

**Comment by isinyaaa** [comment]
> Possible user interface for this feature:
> 
> `kw [env|environment]` `kw env --create ENV_NAME [--keep-local]` `kw env --use ENV_NAME` `kw env --list` `kw env --clean` `kw env --destroy`
> 
> Where `--clean` is a sort of equivalent of `make clean` and `--destroy` is to completely remove the environment. The `--keep-local` option asks kw to keep all the files resulting of a `make build` in the current directory.


Sounds very reasonable.

> _Functionality_ kw env will rely on the -O option of kernel's makefile, allowing for the compilation to a target directory (thus the --keep-local option, to change this behaviour). It will also keep a version of your kworkflow.config and you kernel .config file. Changing envs means changing these two files and the reference to a directory.
> 
> _Desirable features_
> 
> * Provide a shell function to be used in user's `PS1` environmental variable, so that the current kw environment can be shown in one's prompt. For example (already stated above):
> 
> `siqueira@atma ~/Documents/Repositories/kworkflow/kw [master][kw:X86_BUILD]`
> 

So, I had been thinking about that a lot, specially when it comes to other prompts such as zsh and fish, but now I think we can reference [the way `venv` does it](https://github.com/python/cpython/tree/main/Lib/venv/scripts).

> * Upon the creation of one environment, to be able to receive any possible kw option (that is, any option that could go on kworkflow.config) via command line. The configuration of that environment then includes those options in its configuration.
