### ISSUE TITLE
Fix `tests/kwlib_test.sh` usage of `pwd`

### ISSUE THREAD

**Issue by matheustavares** [kworkflow/kworkflow#126]
We test `pwd --help` output at `tests/kwlib_test.sh`. However, this command returns "pwd: pwd [-LP] ..." on newer versions of and "bash: pwd: --: invalid option" on older ones, making the test fail. In this sense, we should refactor this test to be more robust.

**Comment by rodrigosiqueira** [comment]
See: https://github.com/kworkflow/kworkflow/commit/d4b1d33bbcec62a8b0caf7717a5f9499bb2f9bf2

**Comment by matheustavares** [comment]
The main goal with this issue was to allow travis (which used to run on an older Ubuntu version, with our old configurations) to correctly run the said test case. With d4b1d33, however, @rodrigosiqueira already fixed this problem by upgrading the Ubuntu version in our `.travis.yaml` config file.

However, it would still be nice to avoid using the mentioned `pwd` execution as it would still fail in older Ubuntu's. So let's re-open the issue, but removing the kworkflow-alpha milestone (since it's no longer so urgent) and updating the description.
