### ISSUE TITLE
Paplay does not work out of the box

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#157]
Looks like that `paplay` is available on a wide varieties of distros, but it requires some extra package in order to play wav files; I'm not sure, but I think that pulseaudio-alsa package fix this issue. Anyway, we should find out the required package and update our list of dependencies.

**Comment by gbittencourt** [comment]
I have tested it in Arch Linux.
The package pulseaudio-alsa fixed the problem!
