### ISSUE TITLE
Speed up kernel build

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#158]
We should explore more techniques for make `kw build` more powerful. I think we could add support for ccache and maybe tmpfs. Follow some interesting links:
1. https://wiki.archlinux.org/index.php/Ccache
2. https://wiki.debian.org/sbuild#Using_.22ccache.22_with_sbuild
3. https://wiki.debian.org/sbuild#sbuild_overlays_in_tmpfs

**Comment by joaoseckler** [comment]
Possible work breakdown for this issue:
- Provide these features as options in the configuration files;
- Implement setup scripts for ccache and tmpfs;
- Implement the logic for using ccache and tmpfs inside the build functionality of kw;

Benchmark the gain of speed considering different combinations would also be helpful.

**Comment by isinyaaa** [comment]
> We should explore more techniques for make `kw build` more powerful. I think we could add support for ccache and maybe tmpfs. Follow some interesting links:
> 
> 1. https://wiki.archlinux.org/index.php/Ccache
> 2. https://wiki.debian.org/sbuild#Using_.22ccache.22_with_sbuild
> 3. https://wiki.debian.org/sbuild#sbuild_overlays_in_tmpfs

Apparently, distros that use `systemd` (most of them) already have `/tmp` as a [tmpfs by default](https://wiki.archlinux.org/title/Tmpfs#Disable_automatic_mount) (can check that using `findmnt /tmp`. What I think we can do, though, is provide some auto-tweaking options like runtime resizing with

```bash
# mount -o remount,size=$(newsize),noatime /tmp
```

We can also help users with a low memory budget by using [zram or zswap](https://wiki.archlinux.org/title/Improving_performance#zram_or_zswap) which is a lot faster than a normal disk, but still not as good as real memory.

**Comment by isinyaaa** [comment]
> Possible work breakdown for this issue:
> 
> * Provide these features as options in the configuration files;

I agree with that, though it would also be interesting to have some sort of `auto` setting, as we can pretty easily check system specs and autoconfigure some stuff from the get-go.

> * Implement setup scripts for ccache and tmpfs;
> * Implement the logic for using ccache and tmpfs inside the build functionality of kw;

Agree.

> Benchmark the gain of speed considering different combinations would also be helpful.

We could maybe even provide statistics for the users at some point. I'm not sure whether the Pomodoro feature already has something like this, but those could be integrated in some fashion.

**Comment by isinyaaa** [comment]
I actually had conducted a previous experiment with @rodrigosiqueira using a raspberry pi, in which we investigated the effects of using tmpfs. Now I've decided to try doing the same thing locally but exploring a variety of cases, including an exploration of the `GCC_PLUGINS` config, that had been reported to cause many misses and a severe slowdown of a compilation task [1]. The results are as follows:

<details>
  <summary>Kernel compile performace test results</summary>
* compiling with tmpfs
    * vanilla compilation

        ```raw
        Performance counter stats for 'make -j8 vmlinux O=tmpfsdir' (5 runs):

        5,648,918,423,621      instructions:u            #    0.84  insn per cycle           ( +-  0.00% )
        6,766,311,303,171      cycles:u                  #    2.280 GHz                      ( +-  0.01% )
          2,969,791.70 msec cpu-clock:u               #    7.652 CPUs utilized            ( +-  0.02% )

              388.0829 +- 0.0849 seconds time elapsed  ( +-  0.02% )
        ```

    * ccache compilation

        ```raw
         Performance counter stats for 'make CC=ccache gcc -fdiagnostics-color -j8 vmlinux O=tmpfsdir' (5 runs):

           296,915,633,300      instructions:u            #    0.15  insn per cycle           ( +-521.94% )
           257,195,974,035      cycles:u                  #    0.281 GHz                      ( +-659.55% )
                175,320.10 msec cpu-clock:u               #    1.358 CPUs utilized            ( +-422.77% )

                    129.14 +- 93.79 seconds time elapsed  ( +- 72.63% )
        ```

* compiling with gcc plugins + tmpfs
    * vanilla compilation

         ```raw
         Performance counter stats for 'make -j8 vmlinux O=gcctmpfsdir' (5 runs):

         5,649,700,549,329      instructions:u            #    0.84  insn per cycle           ( +-  0.00% )
         6,764,241,035,230      cycles:u                  #    2.275 GHz                      ( +-  0.04% )
              2,972,937.03 msec cpu-clock:u               #    7.647 CPUs utilized            ( +-  0.03% )

                   388.771 +- 0.203 seconds time elapsed  ( +-  0.05% )
        ```

    * ccache compilation

       ```raw
        Performance counter stats for 'make CC=ccache gcc -fdiagnostics-color -j8 vmlinux O=gcctmpfsdir' (5 runs):

          297,937,424,367      instructions:u            #    0.15  insn per cycle           ( +-520.15% )
          258,115,912,747      cycles:u                  #    0.281 GHz                      ( +-657.10% )
               175,597.65 msec cpu-clock:u               #    1.358 CPUs utilized            ( +-422.52% )

                   129.34 +- 93.89 seconds time elapsed  ( +- 72.59% )
       ```

* compiling without tmpfs
    * vanilla compilation

       ```raw
        Performance counter stats for 'make -j8 vmlinux O=notmpfsdir' (5 runs):

        5,648,825,131,933      instructions:u            #    0.84  insn per cycle           ( +-  0.04% )
        6,763,085,266,445      cycles:u                  #    2.273 GHz                      ( +-  0.02% )
             2,975,753.91 msec cpu-clock:u               #    7.631 CPUs utilized            ( +-  0.03% )

                  389.959 +- 0.155 seconds time elapsed  ( +-  0.04% )
       ```

    * ccache compilation

       ```raw
        Performance counter stats for 'make CC=ccache gcc -fdiagnostics-color -j8 vmlinux O=notmpfsdir' (5 runs):

          296,700,364,781      instructions:u            #    0.15  insn per cycle           ( +-522.34% )
          257,556,027,350      cycles:u                  #    0.280 GHz                      ( +-658.08% )
               177,850.36 msec cpu-clock:u               #    1.361 CPUs utilized            ( +-416.95% )

                   130.70 +- 93.83 seconds time elapsed  ( +- 71.79% )
       ```

* compiling with gcc plugins (no tmpfs)
    * vanilla compilation

       ```raw
        Performance counter stats for 'make -j8 vmlinux O=gccnotmpfsdir' (5 runs):

        5,649,556,075,512      instructions:u            #    0.84  insn per cycle           ( +-  0.01% )
        6,761,131,679,935      cycles:u                  #    2.275 GHz                      ( +-  0.03% )
             2,968,912.84 msec cpu-clock:u               #    7.622 CPUs utilized            ( +-  0.08% )

                  389.524 +- 0.320 seconds time elapsed  ( +-  0.08% )
       ```

    * ccache compilation

      ```raw
       Performance counter stats for 'make CC=ccache gcc -fdiagnostics-color -j8 vmlinux O=gccnotmpfsdir' (5 runs):

         297,193,647,244      instructions:u            #    0.15  insn per cycle           ( +-521.30% )
         258,060,972,662      cycles:u                  #    0.281 GHz                      ( +-656.72% )
              177,624.02 msec cpu-clock:u               #    1.359 CPUs utilized            ( +-416.53% )

                  130.67 +- 93.70 seconds time elapsed  ( +- 71.70% )
      ```
</details>

I've also created a gist with the exact same content for reference [2]. And the config used when the `GCC_PLUGINS` config was set to default can also be found in a gist [3]. 

It's quite easy to notice that the `GCC_PLUGINS` complaint doesn't hold, at least not anymore or not on the AMD upstream (used to compile this). You can see that the first compilation with `ccache` turned on in each instance was significantly slower than subsequent ones, thus showing us significant error (around 70% on average vs. something close to 0% when `ccache` was off). Another thing one can easily see is that using `tmpfs` almost didn't change compile times, and that was confirmed in my previous experiment with @rodrigosiqueira, showing that there might not be much of a relationship with the hardware used, but actually with the project in question.

Specs are as follows:

* i7 - 10710U
* 16GB of ram (with the tmpfs's mounted with 8GB), but I think those have a significantly high CAS (upwards of 17) for a low frequency (2666MHz if I'm not mistaken)
* SSD NVMe m.2 WD blue

I'm pretty sure the CPU was the bottleneck in this experiment but I don't think that should mess too much (relatively) with the results displayed.

The config used can be found


[1] - [https://groups.google.com/g/qubes-users/c/phv-NftuM_E](Problems with `GCC_PLUGINS`)
[2] - [https://gist.github.com/isinyaaa/94e32ca20feefb339fb089e4ae6a88d0](perf results)
[3] - [https://gist.github.com/isinyaaa/41c6769d1323bc8528e77d496d1bb8c4](default config (`GCC_PLUGINS` turned on))

**Comment by rodrigosiqueira** [comment]
Hi @isinyaaa ,
Thanks a lot for running all of these tests. It will be awesome if you wrote a blog post about your findings :)
