### ISSUE TITLE
Create a Host deploy option

### ISSUE THREAD

**Issue by giulianobelinassi** [kworkflow/kworkflow#17]
Description Later

**Comment by lms11** [comment]
Description: add feature to use kworkflow as host. This should allow deploying on host.

**Comment by rodrigosiqueira** [comment]
There is a variable named TARGET which can be useful for this issue. Maybe this variable can receive the string "host" and change the normal behavior of kw. Remember that you have to keep kw flexible enough for working with a VM and local machine. If you have any question, do not hesitate to ask me ;)

Ps.: Please, write a detailed description of this feature in the commit message when you finish it ;)

**Comment by rodrigosiqueira** [comment]
Ongoing on KernelInstall branch
