### ISSUE TITLE
Add verbose option

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#179]
Currently, kw deploy and other features throw a lot of information on users. Let's clean up the kw output and add a verbose option if the user wants extra information; this can be a huge task; for this reason, let's break it per feature:

- [x] Verbose mode for deploy;
- [ ] Silent mode for build option;

**Comment by alan-barzilay** [comment]
I'm trying to understand this issue, do you mean stuff like this that is printed in every sub command that imports kwio?
```
/home/barzilay/.local//lib/kw/kwio.sh: line 3: declare: BLUECOLOR: readonly variable
/home/barzilay/.local//lib/kw/kwio.sh: line 4: declare: REDCOLOR: readonly variable
/home/barzilay/.local//lib/kw/kwio.sh: line 5: declare: YELLOWCOLOR: readonly variable
/home/barzilay/.local//lib/kw/kwio.sh: line 6: declare: GREENCOLOR: readonly variable
/home/barzilay/.local//lib/kw/kwio.sh: line 7: declare: SEPARATOR: readonly variable
```

**Comment by rodrigosiqueira** [comment]
Ref: https://github.com/kworkflow/kworkflow/issues/857
