### ISSUE TITLE
Provide build info

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#183]
It is common to check the build info before deploy or just for checking something. For example, developers use:

```bash
make kernelrelease
cat modules.order | wc -l
```

Add a `kw build --info` that provides a build summary, something like:

```bash
kw b -i
Release: 5.6.0-COOL-NAME+
Total modules to be compiled: 158
...
```

**Comment by magalilemes** [comment]
Hello! I'll work on this one :-)

**Comment by rodrigosiqueira** [comment]
Hi,
When I was looking at my local statistics, I had one idea for making this feature more interesting. Since we have access to the local hardware details and statistics, maybe we can display such info as well; something like this:
```
Kernel source info
 Name: 5.6.0-COOL-NAME+
 Release: 5.6.0
 Total modules to be compiled: 158
Build history info
 Time required to compile this kernel: ~4:37
Basic hardware info
 CPU:
   Name: AMD Ryzen 7 PRO 2700
   Frequency: 3200 MHz
 Memory:
   Total memory: ...
   Available Memory: ...
```

We probably need to improve our statistical data collection and add some support for getting hardware data. Keep in mind that we don't need to all of these at once; we can do it in small chunks.
