### ISSUE TITLE
VM prepare

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#2]
Kworkflow works with a qemu images which require a previous installation and configuration. It should be nice to create a command named "kworkflow vm prepare" that create a basic setup for sharing directory and other stuff.

**Comment by giulianobelinassi** [comment]
Could you provide a clearer description regarding this feature? For instance, what is the difference between your request and the deploy rules in `kw prepare`?

**Comment by rodrigosiqueira** [comment]
First of all, thanks for your interest in this issue!

You are right about the prepare option; we already have it. However, this option still not complete and require extra work. Follows some of the wishlists for this feature:
1) We install much more package than we really need in the vm. We have to install only the required packages to avoid wast time.
2) We have to set up things related to ssh stuff.
3) We have to improve the option to prepare the host machine as well (check packages, configuration files, ...)
