### ISSUE TITLE
notify-send package error message

### ISSUE THREAD

**Issue by magalilemes** [kworkflow/kworkflow#219]
Whenever a user invokes a command that sends notifications when finished running, the 'alert' variable in the kworkflow.config file is set to either 'v' or 'vs' and the notify-send package isn't installed, an error message like this is displayed:

`/home/magali/.local//lib/kw/kwio.sh: line 31: notify-send: command not found`

It'd be better if this message wasn't displayed.

**Comment by rodrigosiqueira** [comment]
Hi @magalilemes ,
Thanks a lot for reporting this issue.

We could have something like this:
1. Check if the command set to `visual_alert_command` and `sound_alert_command` exists;
2. If yes, go ahead and execute it;
3. If not, print a warning message that instructs the user to update his config file or disable the alert.
We probably want to execute the above action only if users set the `alert` variable.

**Comment by rodrigosiqueira** [comment]
You can test if a command is installed in your system by using something like this:
```
[ -x "$(command -v foo)" ]
...
if ! command -v COMMAND &> /dev/null
```

**Comment by magalilemes** [comment]
I'm working on this one.
