### ISSUE TITLE
Modernize explore

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#223]
The `explore` feature is old and outdated, and we need to modernize it. I recommend the following steps:

- Create the main entry point to this feature: explore_main.
- Use the new parser system. See `src/build.sh` and `src/deploy` for more references.
- Update and expand unit tests.

See:
https://kworkflow.org/content/project_structure.html#components

**Comment by alan-barzilay** [comment]
I was going to do issue #184, can I tackle both issues in the same PR or should them be separate things?

**Comment by alan-barzilay** [comment]
I think I can work on this one after we merge #180.

Maybe we should create some sort of template for kw to avoid this sort of thing? Something to make it more uniform how we handle different flags, inputs and help

**Comment by harnaman-hk** [comment]
Hi. I can work on this issue.
Currently we use case blocks in both explore_parser and explore. I think we can merge the two.
Are there any other ideas for this?

**Comment by alan-barzilay** [comment]
@harnaman-hk we are also adding a help option for the explore command, to avoid duplicating work I would suggest you make you branch from #180 since it hasn't been merged yet.

**Comment by rodrigosiqueira** [comment]
@hilookas since you already made a PR for the explore feature, could you work on this issue?

**Comment by hilookas** [comment]
@rodrigosiqueira I will investigate it.
