### ISSUE TITLE
Add shellcheck support

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#228]
There is a fascinating lintian tool dedicated to shell script named shellcheck [1]. It would be nice to make kw complaint to many (but not everything) of the shellcheck validations. However, we probably need to conduct this work in three steps:

1. Setup shellcheck in the project;
2. Update the code to follow shellcheck guideline;
3. Integrate shellcheck in our CI.

1. https://github.com/koalaman/shellcheck

**Comment by rodrigosiqueira** [comment]
@alan-barzilay I assigned this issue to you because you said you want to add something like this as part of your project. Keep in mind that we don't need to use spellcheck; it is a suggestion, feel free to suggest anything you want.

**Comment by alan-barzilay** [comment]
I´m already using shellcheck on my machine and I believe it is the best option available. With that said, right now adding it in travis would be useless,  it has to many problems with our current code base. I think the best approach would be to create a PR fixing everything that shellcheck thinks its wrong in kw before adding it as a test in travis. But in the mean time, every kw developer should start using shellcheck locally to avoid introducing more code smells

**Comment by rodrigosiqueira** [comment]
Hhmmm... I'm not sure if we want to be 100% compliant with shellcheck validation. In general, I don't like to follow all the rules checked by these tools; one crucial requirement for a lintian is to ignore some of the things they check. For example, when I use rubcop for Ruby projects, it provides a file that allows me to ignore some lintians check.

Also, if it is possible to add the shellcheck validation per patch we could add it to our CI; this will enable us to avoid new bad code per PR.

**Comment by alan-barzilay** [comment]
> one crucial requirement for a lintian is to ignore some of the things they check. 


Yeah, we can make shellcheck ignore specific warnings, this should be easy once we identify what we want to ignore

**Comment by rodrigosiqueira** [comment]
Hi @alan-barzilay ,
It looks like that shellcheck has many external services for integration. Take a look at something that we can easily see results.

Ref: https://github.com/koalaman/shellcheck/wiki/Integration

**Comment by alan-barzilay** [comment]
https://github.com/wimpysworld/desktopify/blob/master/.github/workflows/shellcheck.yml this project seems to use shellcheck on every PR, I think we can do the same.
We can also run shellcheck on everything, but right now shellcheck finds so many problems on our code base that we should probably just use shellcheck on PRs until we get that sorted out

**Comment by rodrigosiqueira** [comment]
Yeah... we want something like this. Ideally, we want to find a way to run shellcheck per patch.

**Comment by alan-barzilay** [comment]
@rodrigosiqueira can we mark this as done:waiting for stable? Now we have the milestone for sehllcheckcompliance, so I'm ok with closing this, what do you think?

**Comment by rodrigosiqueira** [comment]
Done! Thanks
