### ISSUE TITLE
Add tutorials

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#244]
We need to expand our documentation to add kw tutorials.

**Comment by rodrigosiqueira** [comment]
Hi,
Some of the kw pages that I want that we add:

- [ ] Basic setup
- [ ] How to compile using `kw`
- [ ] How to deploy a new kernel to a remote, local, and vm
- [ ] Config manager
- [ ] Get maintainers and code style check

Ideas? Volunteers?

**Comment by joaoseckler** [comment]
@rodrigosiqueira I'm having a bit of trouble devising what exactly should be in the `basic setup` tutorial. I seems like it should cover kw installation and configuration, but that is already explained in `installanduninstall.rst`. Should we do that again here, in a more beginner-friendly way? I'm also thinking about explaining about ssh setup and qemu setup, is that what you had in mind?

**Comment by joaoseckler** [comment]
Actually, ssh and qemu are pretty well explained in [flusp's tutorial](https://flusp.ime.usp.br/others/use-qemu-to-play-with-linux/)...

**Comment by rodrigosiqueira** [comment]
Hi @joaoseckler 

Do not think about these tutorials as formal documentation. Think about it as something more informal and easy to read, something to be friendly and shows just one path and direction for other details. For this basic setup, I was thinking about the first time that someone sees kw. Think about yourself; what were the challenges and steps you faced for the first time you tried to set up kw? For example, from my perspective (as a maintainer), I constantly guide people through these topics:

1. Clone kw, and I always recommend using the unstable branch;
2. Install kw with `./setup -i` and try `kw version` to see if it is working. If not, try to reload your bash;
3. Go to your kernel repository;
4. Try a simple test such as: kw m drivers/gpu/drm/amd/display/ or kw c drivers/gpu/drm/vkms/
5. Create a local config file with kw init. Next, I explain these config files.
6. Explain that kw can deploy kernel via network and advise the user to setup the ssh in the remote and local machine.

Do not try to explain all the above topics in detail, just show some basic steps and direct users to other documentations. Feel free to reference external websites, and try to not make this huge.

**Comment by joaoseckler** [comment]
thanks @rodrigosiqueira! Your guide was really helpful.

**Comment by rodrigosiqueira** [comment]
https://github.com/kworkflow/kworkflow/pull/565
