### ISSUE TITLE
Add kw man per feature

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#245]
We have `kw [feature] -h`, which provides a command summary. We need to add more details per feature, we can expand this feature to `kw [feature] --help` and display a detailed man per feature.

**Comment by magalilemes** [comment]
I don't know if this relates to this issue, but could we try to standardize the output from `kw [feature] -h`? Compare, for instance, the output from `kw drm -h`, `kw c -h`, and `kw b -h`; they all have different styles.

**Comment by rodrigosiqueira** [comment]
> I don't know if this relates to this issue, but could we try to standardize the output from `kw [feature] -h`? Compare, for instance, the output from `kw drm -h`, `kw c -h`, and `kw b -h`; they all have different styles.

I agree, but I think this should be another issue. Could you create it?

**Comment by rodrigosiqueira** [comment]
Done! Thanks
