### ISSUE TITLE
run_tests prepare throws a warning in unstable

### ISSUE THREAD

**Issue by alan-barzilay** [kworkflow/kworkflow#251]
If I run `./run_tests.sh prepare` in unstable it returns the following message:
`You are ready for running the unit test`
`./run_tests.sh: line 197: return: can only 'return' from a function or sourced script`

Is there a need for this return 0? my understanding is that it would immediately return anyway

**Comment by alan-barzilay** [comment]
@rodrigosiqueira do you know the motivation behind this return statement?

**Comment by rodrigosiqueira** [comment]
@alan-barzilay I think this error happens when the system is already prepared. Try to reproduce this on your side.

**Comment by alan-barzilay** [comment]
yes I believe you are right, but I still think this shouldn´t be happening. I think we should just remove the return statement
