### ISSUE TITLE
Specifying the year in 'kw statistics --year' doesn't seem to work

### ISSUE THREAD

**Issue by magalilemes** [kworkflow/kworkflow#254]
When I run `kw statistics --year`, I get an output showing my 2021 statistics, but when I specify the year, like `kw statistics --year 2021`, I receive the following message:
`Currently, kw does not have any data for the requested year.`
That's weird because kw does have data from 2021. I believe that, in this case, the output from `kw statistics --year 2021` should be the same as `kw statistics --year`.

**Comment by rodrigosiqueira** [comment]
That's weird; I think we have a bug with `--year`. In my case, I have data from 2020 and 2021, but when I try to use `kw statistics --year 2020`, I got the message:

`Currently, kw does not have any data for the requested year.`

Could you take a look at that?

**Comment by magalilemes** [comment]
> Could you take a look at that?
Sure.
