### ISSUE TITLE
Add hardware information in kw statistics

### ISSUE THREAD

**Issue by magalilemes** [kworkflow/kworkflow#269]
This was a suggestion first mentioned in #183. We could show hardware information, such as the CPU model, how much RAM, type of storage device (SSD or HDD) from both host and remote machines.

**Comment by magalilemes** [comment]
It was suggested in the first [PR](https://github.com/kworkflow/kworkflow/pull/314) related to this issue to create a new file in order to deal with the hardware information. With this in mind, should the hardware information still be invoked as part of the `kw statistics` feature, or is it better to have a new option for it (namely, something like `kw device --local`?)

**Comment by rodrigosiqueira** [comment]
It is better to use a new option such as `kw device --local`

**Comment by rodrigosiqueira** [comment]
Done! Thanks
