### ISSUE TITLE
Add signal handling system 

### ISSUE THREAD

**Issue by joaoseckler** [kworkflow/kworkflow#270]
Currently, kw does not handle signals. If you pass it a SIGINT, for example, the subprocess that happens to be executing at that particular moment is the one who will receive and treat it. This results in a poor user interface, where the standard Ctrl-C doesn’t have a meaningful outcome. Worse than that, a simple SIGINT could leave the environment polluted by unremoved temporary files.

Possible breakdown:
 - Implementing a signal manager system for kw. It’s interface should allow the creation of handlers for arbitrary signals and to define at what point in the code execution those handlers are active or not;
 - Implementing default signal manager;
 - Defining a set of directives for kw developers on how to use the signal manager.

**Comment by rodrigosiqueira** [comment]
@joaoseckler could you create a ticket for adding signal handling for ssh and close this ticket after that? Do not forget to assign the new ticket to this milestone.
