### ISSUE TITLE
Implement per command signal handlers

### ISSUE THREAD

**Issue by joaoseckler** [kworkflow/kworkflow#271]
Depends on: #270 

Some commands need specific signal handlers to be able to elegantly be interrupted or halted (e.g. a command that uses temporary files needs to remove those files when receiving a `SIGINT`). Commands that will need specific handlers (but others may need it too):

`mount`, `umount`, `up`, `deploy`, `build`

**Comment by rodrigosiqueira** [comment]
Two important scenarios:

1. When ssh to a machine, and if it suddenly dies, the ssh hangs the terminal, and we have two options: wait until the pc boot up again or close the terminal. Let's handle signals in the `kw s` feature.
2. If we cancel kw deploy, we will leave some old files in the cache directory. Let's clean it.

**Comment by rodrigosiqueira** [comment]
Done! Thanks
