### ISSUE TITLE
Create interface for packaging support

### ISSUE THREAD

**Issue by joaoseckler** [kworkflow/kworkflow#272]
Packaging one’s kernel build is a convenient way to share it with other people. `kw` should handle the process of creating, deploying and building such packages (for example, `dpkg` packages). An distribution-agnostic interface should be created, allowing for the creation, later on, of distribution specific implementations.

**Comment by rodrigosiqueira** [comment]
Hi @joaoseckler ,

Just a couple of notes here:
* We should make this packaging option flexible to users; maybe we can have a config option and also a command-line parameter.
* I think it is important to know the details of the host machine before trying to build a package. I'm not sure if we can build other distros packages without using things like chroot; for this reason, it might be helpful to generate packages based on host distros.
* Make it easy for a developer to get this package.
* Integrate this feature with kw deploy (we can do it later, in another issue);

**Comment by rodrigosiqueira** [comment]
In your PR, use this ticket as a reference.

**Comment by rodrigosiqueira** [comment]
See:
https://github.com/kworkflow/kworkflow/issues/707
