### ISSUE TITLE
Implement support for debian packages

### ISSUE THREAD

**Issue by joaoseckler** [kworkflow/kworkflow#273]
depends on: #272

Implement support for creation, deployment of debian packages.

**Comment by rodrigosiqueira** [comment]
@joaoseckler 
Kernel makefile already supports Debian package creation. I don't remember the exact name, but I think it is something like `make deb-pkg`.

**Comment by rodrigosiqueira** [comment]
See:
https://github.com/kworkflow/kworkflow/issues/707
