### ISSUE TITLE
Document development workflow

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#285]
We have a page that describes how to contribute, but it does not explain anything about the development workflow. We need to create a page that describes:

1. Run unit tests
1. Install and test
1. Run kw locally (./kw)

@alan-barzilay @kwy95 @magalilemes 
Since all of you started in `kw` recently, could some of you work on this issue?

**Comment by magalilemes** [comment]
Sure thing

**Comment by magalilemes** [comment]
> We have a page that describes how to contribute, but it does not explain anything about the development workflow. We need to create a page that describes:
> 
>     1. Run unit tests
> 
>     2. Install and test

@rodrigosiqueira how different should the development workflow page be at describing these two things from the `documentation/content/installanduninstall.rst` and `documentation/content/tests.rst` files?

**Comment by rodrigosiqueira** [comment]
In the development workflow, you just need to focus on the process and point to other documentation pages there; I think it will be short. Also, notice that we do not describe how to use kw using the local repository.

**Comment by rodrigosiqueira** [comment]
@magalilemes 
Another thing that we can document, is the use of shellcheck and shfmt. I think it would be really nice if we show how to configure a git pre-commit for shellcheck and shfmt.
