### ISSUE TITLE
Utilize a code formatter to enforce codingstyle

### ISSUE THREAD

**Issue by alan-barzilay** [kworkflow/kworkflow#290]
Hello everyone, I would like to implement a code formatter to enforce our codestyle and to make our lives easier.
I have found only 2 options that seem reasonable: [beautysh](https://github.com/lovesegfault/beautysh) and [shfmt](https://github.com/mvdan/sh).

They are both under the active development and seem to have strong communities around them, with many plugins for most common IDEs. So I'm not sure which one would be better, shfmt seems to be older and more consolidated, being a multipurpose tool and with many more stars on github.

My suggestion would be to use shfmt, it has a few interesting configurations that can be made to easily match parts of our codestyle and already provides an official pre-commmit hook configuration

```
Printer flags
       -i <uint>
           Indent: 0 for tabs (default), >0 for number of spaces.

       -bn
           Binary ops like && and | may start a line.

       -ci
           Switch cases will be indented.

       -sr
           Redirect operators will be followed by a space.

       -kp
           Keep column alignment paddings.

       -fn
           Function opening braces are placed on a separate line.
```

It also has a simplify method that could be interesting but I haven´t tried it out.
```
       -s
           Simplify the code.

       -mn
           Minify the code to reduce its size (implies -s).
```

Lastly, I figured I should mention this even though I'm not sure if this could be useful.
shfmt can also replace bash -n to check shell scripts for syntax errors. It is more exhaustive, as it parses all syntax statically and requires valid UTF-8:
```
           $ echo '${foo:1 2}' | bash -n
           $ echo '${foo:1 2}' | shfmt >/dev/null
           1:9: not a valid arithmetic operator: 2
           $ echo 'foo=(1 2)' | bash --posix -n
           $ echo 'foo=(1 2)' | shfmt -p >/dev/null
           1:5: arrays are a bash feature

```

Even if we can't configure it to perfectly fit our expectations and our codestyle, if it does a "good enough" job I think we should adopt it. This would help us ensure code quality and style adherence, and more importantly eliminate the back and forth on PRs about formatting.

**Comment by alan-barzilay** [comment]
@rodrigosiqueira @magalilemes @joaoseckler @kwy95 
If you could try shfmt out and let me kwow what is your opinion, I would love to hear your thoughts on this.
`shfmt -i 2 -fn -ln bash` should be pretty similar to our current codestyle, but I haven´t tested all options yet

**Comment by rodrigosiqueira** [comment]
Hi @alan-barzilay , I tested this tool, and it looks super interesting; I really like it since it resembles the checkpatch from the Linux kernel. Though I did not get what you want to achieve here... Do you want to add this as part of the CI to point out codestyle infractions? Or do you want to recommend this as an ancillary tool for development? What your view?

**Comment by alan-barzilay** [comment]
@rodrigosiqueira  both! If we add it as a test in travis we won´t have to keep pestering people for their formation errors. And if we add it as a pre-commit hook we won´t have to worry too much about adhering to code style since it will properly format everything before committing it to the repo.

**Comment by alan-barzilay** [comment]
I found another alternative called [bashate ](https://github.com/openstack/bashate) but shfmt still seems like the better choice

**Comment by rodrigosiqueira** [comment]
Nice, I think shfmt is a good option. The only problem in my view is the fact that we cannot install it with a standard `apt`.

**Comment by alan-barzilay** [comment]
it seems there is a snap option as well. Depending on the IDE/editor you use I believe there are also plugins that take care of that for you, but I agree that not being able to use apt is annoying. I opened a discussion asking about "debian support", considering all the niche platforms they have packages for I find it weird that there is no .deb

**Comment by rodrigosiqueira** [comment]
I used the snap version.
Is snap available for Debian?

Anyway, we can use it in the CI, but I don't feel comfortable enforcing it on the developer's side (by 'it', I mean, any weird installation process). Also, we have to make sure that we choose a solid project to not create a maintenance problem for us in the future.

**Comment by alan-barzilay** [comment]
about debian packaging, it looks like someone wanted to do it and there was support for it but nobody actually followed through with it: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=970393

>  Is snap available for Debian?

I dont use debian, but i think so: https://snapcraft.io/docs/installing-snap-on-debian

>  Also, we have to make sure that we choose a solid project to not create a maintenance problem for us in the future

Agreed, but I think this one is as solid as it can get (at least between the other 2 options)
