### ISSUE TITLE
substitute our codestyle

### ISSUE THREAD

**Issue by alan-barzilay** [kworkflow/kworkflow#291]
I discovered that google has an excellent style guide for shell scripts: https://google.github.io/styleguide/shellguide.html
maybe we should consider adopting it since it is a lot more complete and informative than ours. This would lower our overhead with documentation maintenance, we would only need to maintain codestyle information pertaining to kw, such as the include function or kwio. The only conflict I detected with our codestyle is the braces position on a new line

**Comment by alan-barzilay** [comment]
@rodrigosiqueira

**Comment by rodrigosiqueira** [comment]
I knew about this guide, I think part of our codestyle came from there and from the git project. Honestly, I'm not too fond of the idea of relying on an external style guide; I prefer that we bring what we think is attractive to our codestyle page and adapt it to our goals. Feel free to send PR with parts that you think it is interesting.
