### ISSUE TITLE
test bug: get_today_info_Test sometimes fail

### ISSUE THREAD

**Issue by alan-barzilay** [kworkflow/kworkflow#308]
as noticed in #307, sometimes the get_today_info_Test in kw_time_and_date_Test.sh may fail. 
Looking at the test, this seems to be caused by a race condition. If it so happens that a second is passed between lines 38 and 40, the test will fail. We probably shouldn´t be testing the seconds minutes and hours parts.

**Comment by kwy95** [comment]
Looking at the tests I think this is an inevitability of the way these tests and `get_today_info()` were implemented, currently during the test the `date` command is called 3 times in succession, which will yield 3 slightly different times, when those times happen to cross the seconds mark this test will fail.
I can think of 3 ways to alleviate this problem:

1. We stop testing the seconds.
2. We add an arbitrary margin of error for this test.
3. We redo the test if it fails once.

Not sure which one we should go for if we decide to change anything, but I think the first two would definitely be the easier but the third one is probably more robust.

**Comment by alan-barzilay** [comment]
I agree. Honestly I think we should just pick whichever option is easier to implement, all your suggestions are reasonable

**Comment by rodrigosiqueira** [comment]
https://github.com/kworkflow/kworkflow/commit/f984b81c456d138bda53e7715e220afea6404b8e
