### ISSUE TITLE
Installation always appends to `.zshrc`

### ISSUE THREAD

**Issue by kwy95** [kworkflow/kworkflow#309]
Whenever I run `./setup.sh -i` it appends the same lines to my `.zshrc` file, when I checked my file it had well over 20 repetitions of the same lines at the end. It was slowing down my environment loading
We should do a check to see if the lines need to be added, or maybe just source a file for the settings. Or some other solution as to not clutter the users settings.

**Comment by rodrigosiqueira** [comment]
@alan-barzilay @kwy95 since you two use zsh, could you take a look at that?

**Comment by alan-barzilay** [comment]
This also happens with .bashrc, I believe this is a problem with how we deal with tab completion in general. In a best case scenario we shouldn't have to touch the bashrc and zshrc files

**Comment by rodrigosiqueira** [comment]
I don't see this issue with `.bashrc`.

**Comment by rodrigosiqueira** [comment]
@alan-barzilay @kwy95 any progress here?
