### ISSUE TITLE
SC2124 - Assigning an array to a string! Assign as array, or use * instead of @ to concatenate

### ISSUE THREAD

**Issue by alan-barzilay** [kworkflow/kworkflow#318]
This issue will be used to keep track of an error/warning type that is common on our codebase. For more information about it, take a look at the official shellcheck wiki entry:
https://github.com/koalaman/shellcheck/wiki/SC2124

**Comment by alan-barzilay** [comment]
Related error: 
https://github.com/koalaman/shellcheck/wiki/SC2178

**Comment by alan-barzilay** [comment]
@joaoseckler It seems like we missed a few files:

In src/plugins/kernel_install/kernel_install_utils.sh line 39:
  local message=$@
                ^-- SC2124: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.


--
In src/plugins/kernel_install/utils.sh line 39:
  local message=$@
                ^-- SC2124: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.


--
In src/plugins/subsystems/drm/drm.sh line 129:
  local raw_modules_str="$@"
                        ^--^ SC2124: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.


In src/plugins/subsystems/drm/drm.sh line 346:
  local raw_options="$@"
                    ^--^ SC2124: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.

**Comment by alan-barzilay** [comment]
also one for SC2178

In tests/utils.sh line 243:
  local expected="$3"
        ^------^ SC2178: Variable was used as an array but is now assigned a string.

**Comment by alan-barzilay** [comment]
Maybe this 2 error codes are also related? dont know, what do you think joao?

In tests/utils.sh line 243:
  local expected="$3"
        ^------^ SC2178: Variable was used as an array but is now assigned a string.

In tests/utils.sh line 248:
  assertEquals "line $line: $msg" "$target" "$expected"
                                             ^-------^ SC2128: Expanding an array without an index only gives the first element.

**Comment by rodrigosiqueira** [comment]
Done! Thanks
