### ISSUE TITLE
SC2086 -  Double quote to prevent globbing and word splitting.

### ISSUE THREAD

**Issue by alan-barzilay** [kworkflow/kworkflow#321]
This issue will be used to keep track of an error/warning type that is common on our codebase. For more information about it, take a look at the official shellcheck wiki entry:
https://github.com/koalaman/shellcheck/wiki/SC2086

**Comment by alan-barzilay** [comment]
A related error:

SC2231 - Quote expansions in this for loop glob to prevent wordsplitting, e.g. "$dir"/*.txt .
https://github.com/koalaman/shellcheck/wiki/SC2231

**Comment by magalilemes** [comment]
I'm calling dibs on this one.

**Comment by rodrigosiqueira** [comment]
Done! Thanks
