### ISSUE TITLE
SC2199 -  Arrays implicitly concatenate in [[ ]]. Use a loop (or explicit * instead of @).

### ISSUE THREAD

**Issue by alan-barzilay** [kworkflow/kworkflow#323]
This issue will be used to keep track of an error/warning type that is common on our codebase. For more information about it, take a look at the official shellcheck wiki entry:
https://github.com/koalaman/shellcheck/wiki/SC2199

**Comment by alan-barzilay** [comment]
@magalilemes this issue seems to happen in the statistics and pomodoro files (maybe in other files too), since you have been working on them would you mind helping me with this?
I would also like to know your opinion, do you agree this is an issue that should be fixed?
@rodrigosiqueira I would like your opinion too, sorry I missed this error in our meeting

**Comment by magalilemes** [comment]
> @magalilemes this issue seems to happen in the statistics and pomodoro files (maybe in other files too), since you have been working on them would you mind helping me with this?
> I would also like to know your opinion, do you agree this is an issue that should be fixed?

@alan-barzilay Sure thing. I think the rationale behind this warning makes total sense. Will look into it.
