### ISSUE TITLE
Update kw sound alert

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#333]
When Joao was packaging kw for Debian, we realize that the `complete.wav` does not have the correct attribution to the original author (https://github.com/kworkflow/kworkflow/tree/master/sounds). Unfortunately, I couldn't find where I downloaded it, and for this reason, we need to replace this sound. In this sense, I'm looking for suggestions for a new set of sound alerts for kw; I want to add five options, but one of them will be the default one. The audio should follow these requirements:

1. It should be under creative commons license;
2. We should be able to hear it even if we are listening to music;
3. It should use something that does not give a fright;

This website has many samples:
https://freesound.org/

@kwy95 @magalilemes @joaoseckler @alan-barzilay @melissawen I'm open for suggestions.

**Comment by joaoseckler** [comment]
Is this a duplicate of #317?

**Comment by rodrigosiqueira** [comment]
Done! Thanks
