### ISSUE TITLE
Pomodoro should check if `pomodoro_current.log` exists

### ISSUE THREAD

**Issue by joaoseckler** [kworkflow/kworkflow#357]
A first time user running `kw p -l` will get an error saying the file doesn't exist.

Possible solutions:

- Add a  `[ -f "$POMODORO_LOG_FILE" ]` test [here](https://github.com/kworkflow/kworkflow/blob/bc3491147d0a4dbf59f93f5db4674f1a9cd00fe8/src/pomodoro.sh#L275) and print a warning and exit if it doesn't exist

- `touch` the file before reading it for a silent solution

**Comment by rodrigosiqueira** [comment]
https://github.com/kworkflow/kworkflow/commit/f984b81c456d138bda53e7715e220afea6404b8e
