### ISSUE TITLE
SC2091: Remove surrounding $() to avoid executing output (or use eval if intentional).

### ISSUE THREAD

**Issue by alan-barzilay** [kworkflow/kworkflow#366]
https://github.com/koalaman/shellcheck/wiki/SC2091

A lot of tests seem to have this error

**Comment by rodrigosiqueira** [comment]
I think it makes sense to handle these warnings since it can point to some valid cases such as the one discussed here https://github.com/kworkflow/kworkflow/pull/376.

**Comment by rodrigosiqueira** [comment]
Done! Thanks
