### ISSUE TITLE
 SC2012 - Use find instead of ls to better handle non-alphanumeric filenames.

### ISSUE THREAD

**Issue by alan-barzilay** [kworkflow/kworkflow#373]
https://github.com/koalaman/shellcheck/wiki/SC2012

Not sure what to do with this one, I understand its reasoning but it looks like it would make the code more bloated since find would need many other flags. We currently have 2 occurrences of this error:

```
In tests/configm_test.sh line 430:
  ret=$(ls configs/configs -1 | wc -l)
        ^-------------------^ SC2012: Use find instead of ls to better handle non-alphanumeric filenames.


In tests/configm_test.sh line 436:
  ret=$(ls configs/configs -1 | wc -l)
        ^-------------------^ SC2012: Use find instead of ls to better handle non-alphanumeric filenames.
```

**Comment by alan-barzilay** [comment]
@rodrigorsdc do you have any thoughts on this?

**Comment by rodrigosiqueira** [comment]
Hi,
After thinking about this, I think it makes sense to use the find command. One of the reasons is the fact that `ls` has different behavior across distros. The `find` command can make the kw behavior more reliable.

**Comment by rodrigosiqueira** [comment]
Done! Thanks
