### ISSUE TITLE
test_show_data failing on unstable

### ISSUE THREAD

**Issue by alan-barzilay** [kworkflow/kworkflow#374]
For some reason the test_show_data from the report_test file seems to be failing locally on my machine. I'm on unstable and synchronized with the main repo. Anyone else with the same problem?
(on a side note, test_grouping_year_data takes a long time to run, is this expected?)

```
Running test [report_test]
=========================================================
test_report_parse
test_expand_time_labels
test_grouping_day_data
test_grouping_week_data
test_grouping_month_data
test_grouping_year_data
test_show_data
shunit2:ERROR test_show_data() returned non-zero return code.
test_save_data_to

Ran 8 tests.

FAILED (failures=1)
```

**Comment by magalilemes** [comment]
It's failing for me too. I guess it's a version issue again, as it fails if I use shunit2 v2.1.8, but not if I use v2.1.7 or 2.1.6-1.1ubuntu1 from apt.
