### ISSUE TITLE
shellcheck and quotes

### ISSUE THREAD

**Issue by alan-barzilay** [kworkflow/kworkflow#375]
These 4 shellcheck errors are kinda similar  

https://www.shellcheck.net/wiki/SC2046 -- Quote this to prevent word splitting
https://www.shellcheck.net/wiki/SC2053 -- Quote the right-hand side of != in [[ ]] to prevent glob matching.
https://www.shellcheck.net/wiki/SC2076 -- Remove quotes from right-hand side of =~, it'll match literally rather than as a regex.
https://github.com/koalaman/shellcheck/wiki/SC2206 -- Quote to prevent word splitting/globbing, or split robustly with mapfile or read -a.

**Comment by alan-barzilay** [comment]
#321 also dealt with 2 similar errors dealing with quotes

**Comment by rodrigosiqueira** [comment]
Done! Thanks
