### ISSUE TITLE
Respect XDG config standard locations 

### ISSUE THREAD

**Issue by aurabindo** [kworkflow/kworkflow#385]
Make kw look for configuration file in ~/XDG_HOME/.config as per the standard https://wiki.archlinux.org/title/XDG_Base_Directory
XDG might only apply for GUI applications, so I'm not sure if a CLI application like kw should bother, but i think a natural second choice for the config file after the system wide location `/etc/kw` could be assumed to be in `~/.config/kw`

**Expected behavior**
Prioritize a config present in `~/.config/kw/` over  `~/.local/etc/kw/`

**Comment by alan-barzilay** [comment]
possible duplicate with #296.

PS: XDG does apply for non-GUI applications :)

**Comment by aurabindo** [comment]
I agree! Other than the XDG dir, my first instinct would be look for a `~/.kworkflow` rather than in `~/.local/etc/`

**Comment by rodrigosiqueira** [comment]
We already have full support for XDG in the unstable and master branch.
Thanks for the help with this issue.
