### ISSUE TITLE
kw s doesn't use ssh_user set in kworkflow.config

### ISSUE THREAD

**Issue by lpstankus** [kworkflow/kworkflow#395]
**Describe the bug**
When executing `kw s`, kworkflow uses the host's machine user for the ssh connection instead of the `ssh_user` set in `kworkflow.config`.

**To Reproduce**
Set an user to the `ssh_user` field in the `kworkflow.config` and execute `kw s`.

**Expected behavior**
The command should ssh to the user set in `ssh_user`.

**Desktop**
 - OS: Arch Linux
 - Version: unstable branch
 - Bash Version 5.1.8(1)-release

**Comment by rodrigosiqueira** [comment]
I'm going to work on this issue and at the same time rework `kw ssh`.
