### ISSUE TITLE
kw b -i shows some unexpected messages

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#398]
**Describe the bug**
After building an x86 kernel, I tried `kw b -i` and got some makefile messages.

**To Reproduce**
1. Compile an x86 kernel
2. Use kw b -i

**Expected behavior**
Just info messages handled by kw.

**Message**
`arch/x86/Makefile:148: CONFIG_X86_X32 enabled but no binutils support`

**Desktop (please complete the following information):**
 - OS: Ubuntu  20.01
 - Version: kw from unstable branch
 - Bash Version: 5.0.7

**Comment by magalilemes** [comment]
At first, this seems like a problem outside of kw. The warning message comes from running `make kernelrelease`. I ran this command in kernel v5.13 and 5.14 and got the warning, but if I git checkout to v5.12, v5.11, v5.10, ..., I don't get the warning. Does this happen to you too?

**Comment by alan-barzilay** [comment]
@magalilemes the same happened with me
