### ISSUE TITLE
Create `vm` option and move mount, umount, and up under it.

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#453]
For historical reasons, we have some commands associate with a virtual machine (VM) in the first set of operations provided by kw. Those options are:

* mount,mo
* umount,um
* up,u

It does not make sense to have these options like that. We need to move all of these options under `vm` flag; for example, we should have:
```
kw vm --mount
kw vm --umount
kw vm --up
```

**Comment by eduardopinheiro** [comment]
I'm working on this issue

**Comment by eduardopinheiro** [comment]
@rodrigosiqueira Sorry about the delay, I got caught up in some work and masters things I had to do and didn't have much time to work on this. But I've been fixing the problems pointed out in the review and I should be able to resend the PR in a few days.
