### ISSUE TITLE
Avoid using rst2man every time

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#455]
We use a tool named rst2man to convert rst pages to the man format. We do it in real-time, which can be unnecessarily slow; let's use rst2man to create the final man page in the `setup.sh` file and avoid extra processing on the user side.

**Comment by Pedro84skynet** [comment]
I would like to help on this one, but if you can help me understand one thing or two first, i would be gratefull ...after a command like "kw man build" ...for instance, kw calls `kworkflow_man()`, from `help.sh`, that calls `cmd_manager` to handle the SILENCE flag... and then invoke `"man -l"`  which make use of the .1 files on `./local/share/kw/man`, there is no real time convertion in kw man call in terminal, right? so where that real time conversion take place in `setup.sh`? is in...`cmd_output_manager "sphinx-build -nW -b man $DOCUMENTATION $mandir" "$verbose"` ...under `synchronize_files()`? ...Thanks in advance!

**Comment by kwy95** [comment]
Sorry, this was opened as a mistake. It used to be done on the fly with `rst2man`, but we have already patched this functionality and now it works as you describe.
