### ISSUE TITLE
Add autocomplete per feature

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#458]
Currently, we only have auto-complete for major features. It would be nice to have auto-completed per parameters inside each feature.

**Comment by lucastheo** [comment]
Team UFABC are working this issue

**Comment by rodrigosiqueira** [comment]
PR merged to the unstable branch. Thanks.

**Comment by rodrigosiqueira** [comment]
https://github.com/kworkflow/kworkflow/commit/f984b81c456d138bda53e7715e220afea6404b8e
