### ISSUE TITLE
setup.sh -i shows pip error message if a dependency is missing

### ISSUE THREAD

**Issue by kwy95** [kworkflow/kworkflow#460]
**Describe the bug**
While attempting to install kw if the machine is missing a distro dependency but not a pip dependency then the program outputs a pip install error after installing the distro dependency.
This is the error message:
```
ERROR: You must give at least one requirement to install (see "pip help install")
```

**To Reproduce**
Ensure you have all pip dependencies installed and at least one distro dependency missing, then run `./setup.sh -i`.

**Expected behavior**
Any missing dependency should be installed with no errors.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 21.04
 - Bash Version: 5.1.4(1)-release

**Comment by rodrigosiqueira** [comment]
https://github.com/kworkflow/kworkflow/commit/f984b81c456d138bda53e7715e220afea6404b8e
