### ISSUE TITLE
Differentiate includes more robustly

### ISSUE THREAD

**Issue by isinyaaa** [kworkflow/kworkflow#500]
As per @kwy95's suggestion, multiple characters are being substituted by underscores in `kw_include.sh`'s included paths, which may lead to various paths having the same variable name. So some method for differentiating those paths is necessary, among the suggested ones is some sort of hashing.

> It also dawned on me that since we are substituting all invalid characters with underscores we might eventually have different files that produce the same variable name. A potential workaround for this is to add some sort of hash based on the full path to the end of the variable name. But this might increase the overhead too much, so maybe we should just add this PR once it gets updated and worry about this hashing business later.

_Originally posted by @kwy95 in https://github.com/kworkflow/kworkflow/pull/474#pullrequestreview-787548192_

It might also be interesting to notice the security implication of different versions of `sha`: _https://www.keycdn.com/support/sha1-vs-sha256_

Also, notice that these versions don't have much bearing on runtime:

![image](https://user-images.githubusercontent.com/39812919/138974005-4bcb31c6-874a-42f3-9c1f-d638ce652809.png)

**Comment by isinyaaa** [comment]
It's interesting to notice that the **very weak** `sum` command is actually really fast, so it might be interesting for our particular use case so that we can maintain kw responsive.

![image](https://user-images.githubusercontent.com/39812919/141871818-9079c12e-cf59-4dc4-a3ee-abb977ec01df.png)

@kwy95 @rodrigosiqueira comments?

**Comment by rodrigosiqueira** [comment]
Thanks a lot for this great PR!
Merged to the unstable branch.
