### ISSUE TITLE
kw report -o does not validate given path

### ISSUE THREAD

**Issue by kwy95** [kworkflow/kworkflow#532]
**Description:**

There is no path validation when generating a report, this leads to problems if a directory or an invalid path is given.

**How to Reproduce:**

Execute `kw report -o ./`

**Expected behavior:**

We should implement a validation for the given path and auto generate a file name if a directory is given.

**Comment by emanuellima1** [comment]
Not reproducible. Bug already fixed.

**Comment by aquilamacedo** [comment]
Hi, @emanuellima1.  I'm working on this issue. The bug is still reproducible. If you use the unstable branch and try to run the command `./kw report -o ./` you will still get the error.
