### ISSUE TITLE
Improve assert_equal_help output

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#554]
**Description:**

Let's make `assert_equal_help` display the failure case as:

 Expected Result: <something>
 ->Actual Result: <something>

Maybe we can show the expected result in blue colors and the failure in red.

**Type:** Refactor

**Why:**

Currently, `assert_equal_help` shows the actual output and the expected result next to each other, which is not friendly.

**Comment by RaviRahar** [comment]
@rodrigosiqueira This is my first contribution here. does this seem alright?
