### ISSUE TITLE
Ambiguity in Tutorial

### ISSUE THREAD

**Issue by utkarsh181** [kworkflow/kworkflow#575]
Hello,

First of all, thank you for `kworkflow`.

Tutorial ["How to Install a New Kernel"](https://kworkflow.org/tutorials/deploy-kernel.html#remote-machine-deploy) list command `kw deploy --setup`, but its failing with the error:

```
$ kw deploy --setup
kw deploy: unrecognized option '--setup'
```

**Comment by rodrigosiqueira** [comment]
Hi @utkarsh181 ,
Could you paste the output of `kw version`? Also, which distro are you using in your host and target?

**Comment by utkarsh181** [comment]
On 2022-03-16, 04:22 -0700, Rodrigo Siqueira Jordão ***@***.***> wrote:

> Hi @utkarsh181 ,

> Could you paste the output of `kw version`?

```
kw version
alpha
Branch: master
Commit: f984b81
```

> Also, which distro are you using in your host and target?

Both are Arch Linux, although later is running custom kernel as defined
in tutorial [Kernel Compilation and
Installation](https://flusp.ime.usp.br/others/Kernel-compilation-and-installation/).

**Comment by utkarsh181** [comment]
> Could you paste the output of `kw version`?

```
$ kw version
alpha
Branch: master
Commit: f984b81
```

> Also, which distro are you using in your host and target?

Both are Arch Linux, although later is running custom kernel as defined
in tutorial [Kernel Compilation and Installation](https://flusp.ime.usp.br/others/Kernel-compilation-and-installation/).

**Comment by rodrigosiqueira** [comment]
@utkarsh181 Try kw from the unstable branch, I did not sync our main branch yet.

**Comment by utkarsh181** [comment]
> @utkarsh181 Try kw from the unstable branch, I did not sync our main branch yet.

Thank you, its working.
