### ISSUE TITLE
Use `ID_LIKE` key to identify distros

### ISSUE THREAD

**Issue by kwy95** [kworkflow/kworkflow#605]
**Description:**

I recently started using a new distro (EndeavourOS) which is essentially arch, and the installation was halted as *kw* didn't recognize the distro. I circumvented the problem by adding a new key, specific to this new distro, and I realized that this might not be the best way of doing things. Studying the install steps, I discovered that some distros provide the `ID_LIKE` key to their configurations. This key stores the "parent" distro, so for Ubuntu is Debian, for EndeavourOS is Arch, etc. I am proposing we rework the install process to use this key instead, which would allow for instant support to a lot of distros. I expect that not all distros would have the `ID_LIKE` key, so the `ID` key would be used as a last resort.

As pointed out by @isinyaaa, the main reason we identify user distro is to select which package manager to use to install *kw*'s dependencies. This presents a potential problem because it's possible for a system to be based on say, Debian, but use a package manager that is not `apt`.

**Type:**

Refactor.

**Why:**

This would make the install process easier for derivative distros.

**Comment by kwy95** [comment]
This is based on a discussion started at #597

**Comment by rodrigosiqueira** [comment]
Hi @kwy95 @isinyaaa ,

I'm working to enable kw deploy to some other ArchLinux-based distro, but I thought it would be good to address this issue first. What do you think of this first draft?

```diff
diff --git a/src/kwlib.sh b/src/kwlib.sh
index ce6dcb9..fe89bb3 100644
--- a/src/kwlib.sh
+++ b/src/kwlib.sh
@@ -288,7 +288,12 @@ function detect_distro()
   if [[ -n "$str_check" ]]; then
     distro_id="$str_check"
   elif [[ -d $etc_path ]]; then
-    distro_id=$(cat "$etc_path"/*-release | grep -w ID | cut -d = -f 2)
+    distro_id=$(cat "$etc_path"/*-release | grep -w ID_LIKE | cut -d = -f 2)
+
+    # It is not a derivative distro; let's check ID.
+    if [[ -z "$distro_id" ]]; then
+      distro_id=$(cat "$etc_path"/*-release | grep -w ID | cut -d = -f 2)
+    fi
   fi
 
   # Debian family
diff --git a/src/remote.sh b/src/remote.sh
index c870d25..2e66bbe 100644
--- a/src/remote.sh
+++ b/src/remote.sh
@@ -160,8 +160,19 @@ function which_distro()
   local user=${3:-${remote_parameters[ssh_user]}}
   local flag=${4:-'SILENT'}
 
+  cmd='cat /etc/os-release | grep -w ID_LIKE | cut -d = -f 2'
+  output=$(cmd_remotely "$cmd" "$flag" "$remote" "$port" "$user")
+
+  # ID_LIKE: We know it is a derivative distro
+  if [[ -n "$output" ]]; then
+    printf '%s' "$output"
+    return
+  fi
+
+  # It is not a derivative distro; let's check ID.
   cmd='cat /etc/os-release | grep -w ID | cut -d = -f 2'
-  cmd_remotely "$cmd" "$flag" "$remote" "$port" "$user"
+  output=$(cmd_remotely "$cmd" "$flag" "$remote" "$port" "$user")
+  printf '%s' "$output"
 }
```

Tbh, I'm not happy with those extra "if". This is more harmful in the `which_distro` because we need to open and close an ssh connection twice. Any ideas?

**Comment by kwy95** [comment]
My suggestion is to retrieve both values at the same time, and use the value referring to `ID` as a fallback, either when the first value is not present or simply not in our distros list. This should deal away with the double connection.
