### ISSUE TITLE
`kw configm --save` returns fatal git error

### ISSUE THREAD

**Issue by mairacanal** [kworkflow/kworkflow#625]
**Description:**

When I run `kw configm --save` inside the Linux repository, it returns a fatal git error. The command saves the .config file, but the git fatal error can be confusing to new users.

**How to Reproduce:**

➜ cd linux

➜ kw configm --save "STD_DCN_CONFIG"
STD_DCN_CONFIG already exists. Update? [y/N]: y
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/home/mairacanal/.local/lib/kw/config_manager.sh: line 134: fail: command not found

**Expected behavior:**

It would be expected that no git error would be shown, and kw returns a success message.

**System information:**

 - OS: Fedora 35
 - kw Version: kw @3e1edcb
 - Bash Version: version 5.1.8(1)-release (x86_64-redhat-linux-gnu)

**Comment by rodrigosiqueira** [comment]
Hi @mairacanal , I'm not able to reproduce this issue. Maybe I'm missing something...
Do you have `.git` in this kernel tree?

**Comment by mairacanal** [comment]
Still reproducible on F36 and kw @2e69b63. There is `.git` in this kernel tree.

I have multiple problems with `kw k`. I get this git fatal error when saving a config file and cannot delete config files with the `kw k --remove`.

About the git fatal error, by taking a look at the code, I would say that the git repository was not correctly created on the `.local/share/kw/configs`. Then, when trying to add a config file, the `git commit` command fails.

**Comment by magalilemes** [comment]
On this note, I wonder why / what are the advantages of wrapping git commands around `kw k`. We could, for instance, only  use `rm` instead of `git rm`, etc.
But if git commands are advantageous enough, maybe checking if .git was successfully created (or if it exists) in `.local/share/kw/configs` might be a start.

**Comment by rodrigosiqueira** [comment]
@mairacanal @magalilemes we had a refactor in this feature. Could you check if you can reproduce this issue in the unstable branch?

**Comment by magalilemes** [comment]
@rodrigosiqueira I'm not able to reproduce this anymore.

**Comment by rodrigosiqueira** [comment]
@mairacanal could you confirm if this is still an issue on the latest version?

**Comment by mairacanal** [comment]
Not reproducible anymore! Thanks!

**Comment by rodrigosiqueira** [comment]
Thanks for checking!
