### ISSUE TITLE
Use the arch variable in the kw b

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#63]
Now we have the information about the compilation architecture in the kworkflow.config. How about starting to use it?

**Comment by barbaradcf** [comment]
How could this information be used?

**Comment by MatheusBernardino** [comment]
Hi @barbaradcf . First, thanks for the interest in this issue!

Just a little intro, before we get into the issue itself: Kw uses a system of global and local configuration files (which you can read about at README.md). The configuration file defines, among other things, a setting named `arch` which contains the architecture to be used for kw commands related to kernel, in general. (The default value for `arch` is `x86_64`).

When running a `kw b`, to compile kernel and it's modules, the function `mk_build` (at `src/mk.sh`) is called. Currently, this function uses a `$MAKE_OPTS` variable which should contain, in theory, the options for make. But this variable does not exist.

This issue consists in two things:
1) removing `$MAKE_OPTS`
2) Using `ARCH=${configurations[arch]}` as a make option at `mk_build` (note that `${configurations[arch]}` will be the setting defined at configuration file, I said earlier. The `src/commons.sh` parse settings at configuration files and store them at the hash `$configurations`)
