### ISSUE TITLE
kw deploy fails finding kernel image

### ISSUE THREAD

**Issue by magalilemes** [kworkflow/kworkflow#641]
**Description:**
When I run `kw d`, `build_config[arch]` is not filled, leading to the following error:

```
$ kw d
* Preparing modules
[=====================================================================================================================================================================================================================================>] 100%
* Sending kernel modules (5.18.0-rc5-GLIMPSE+) to the remote
    110,922,551 100%   48.67MB/s    0:00:02 (xfr#1, to-chk=0/1)
We could not find a valid kernel image at arch//boot
Please, check if your compilation successfully completed or
check your kworkflow.config
```

**How to Reproduce:**

```
# Inside a Linux kernel repository:
kw init    # make sure you have both kworkflow.config and build.config inside .kw
kw build
kw deploy  # I'm deploying to a remote machine
```

**Expected behavior:**

I expect `kw d` to find the kernel image.

**System information:**

 - OS:
 Fedora Linux 36 (Workstation Edition)
 - kw Version:
alpha
Branch: unstable
Commit: 8597334
 - Bash Version:
 5.1.16(1)-release

**Additional context:**

I believe that `build.config` is not parsed in `kw deploy`. It is parsed in `kw build`, so `kw bd` works just fine, but `kw d` doesn't.

**Comment by rodrigosiqueira** [comment]
@magalilemes did it happens in a local deploy? I tried to reproduce this by using kw d in a remote machine, but everything works as expected.

**Comment by magalilemes** [comment]
@rodrigosiqueira Nope, the deploy target is set to remote.
