### ISSUE TITLE
test/deploy_test.sh fails because "grub-mkconfig" is not findable by kw 

### ISSUE THREAD

**Issue by Kamorst** [kworkflow/kworkflow#654]
**Description:**

  `./run_tests.sh test deploy_test.sh ` fails on Debian with the given output:
```
test_kernel_install_arm_local_no_config
ASSERT:line 651, statement 5:
Expected: "sudo -E grub-mkconfig -o /boot/grub/grub.cfg"  
but got:  "There is no grub-mkconfig command in the system."
```

**How to Reproduce:**

Execute `./run_tests.sh test deploy_test.sh`.

**Expected behavior:**

No failed tests.

**System information:**

 - OS: Debian 11 (bullseye)
 - kw Version: 
``` 
alpha
Branch: unstable
Commit: 2e69b63
```
 - Bash Version: GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)

**Additional context:**

  Running `PATH+=:/usr/sbin` before running the test makes all test pass. I suppose that's because in Debian, in particular, `grub-mkconfig` is not in the PATH of a non-root user. Digging inside the code, the function `command_exists()` (src/plugins/kernel_install/utils.sh) do not find `grub-mkconfig`.

**Comment by Kamorst** [comment]
I don't know how easy it is to add different test distros (like Arch and Debian) on travis-ci but would reduce this kind of bug reports.

**Comment by kwy95** [comment]
I did a small search, and it seems that github only offers the [ubuntu distro] for their runners. This means we would have to set up [self-hosted runners] for the different distros, which seems to be [somewhat] [involved]. And even then it seems that there is no support for [Arch], for example.

[ubuntu distro]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
[self-hosted runners]: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners
[somewhat]: https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners
[involved]: https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow
[Arch]: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#supported-architectures-and-operating-systems-for-self-hosted-runners

**Comment by rodrigosiqueira** [comment]
To fix this issue, we need to add a test mock for the `grub-mkconfig` command when we run tests related to local deploy. The challenge here came from this line:

https://github.com/kworkflow/kworkflow/blob/unstable/src/deploy.sh#L1073

Notice that we include those files when we execute the function, which makes it a little bit challenging to mock grub-mkconfig.

**Comment by rodrigosiqueira** [comment]
I think this issue is not valid anymore; if you can repro this issue, feel free to re-open it.
