### ISSUE TITLE
Modernize diff

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#660]
The `diff` feature is old and outdated, lets:
-  Use the new parser system
-  Use a better way to display data
-  Update and expand unit tests

**Comment by fernandohjunqueira** [comment]
Me and @GuilhermeMoreno are working on this issue.

**Comment by davidbtadokoro** [comment]
> @rodrigosiqueira me and @GuilhermeMoreno inserted a missing test for this issue. @davidbtadokoro merged it. Shouldn't this issue be closed? Is there anything missing for us to solve related to modernizing diff?

Hey guys, you are right. I probably forgot to add the 'Done: wait for stable' tag after merging the change, and that is why the issue wasn't closed. Thanks for the heads up, doing it now!
