### ISSUE TITLE
Diff folders to show files in one folder but not the others

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#661]
**Description/Why:**

Sometimes a developer might want to find out files that are in one kernel tree but not in another one. It might be useful to support this type of diff under the `kw diff`.

**Targeted users:**

* Developers that work with multiple trees

**API draft:**

```bash
kw diff folder-one folder-two
- file-y
- file-h
```
Maybe a good start point, could be this command:

```
diff <(cd dir1; ls) <(cd dir2; ls)
```
or
```
diff -rq tests/amdgpu/ ../another-tree/tests/amdgpu/
```

**Comment by emanuellima1** [comment]
Working on this.
