### ISSUE TITLE
Replace the progress bar with something else

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#675]
**Description:**

When we deploy a new kernel to a target machine, we have a progress bar that looks like this:

```
$ kw d
* Preparing modules
[=========================================================================================
```

This progress bar is constantly broken due to how we find the maximum value to calculate the current percentage. It is not doable to maintain this type of progress bar working as expected since it can change based on the user config file.

**Type:**

Refactor

**Why:**

Instead of trying to show a percentage, let's just show the elapsed time and a spinner.

**Comment by emanuellima1** [comment]
Working on it. To clarify, do we show the elapsed time at the end of the command or a timer that progresses as the command is run?
