### ISSUE TITLE
Improve "kw m --authors" for multiline MODULE_AUTHOR statements

### ISSUE THREAD

**Issue by matheustavares** [kworkflow/kworkflow#69]
When we run a `kw m --authors`, only authors found in a single line MODULE_AUTHOR statement are captured and printed. In the future, it would be nice to look for multiline MODULE_AUTHOR statements such as:

```
MODULE_AUTHOR ("a_long_email@xx.com" \
               "another_long@yy.com" )
```

and:

```
MODULE_AUTHOR ("a_long_email@xx.com"
               "another_long@yy.com" )
```

which are, both, valid C statements. In the currently implementation neither of these four emails would be printed.

**Comment by Lincoln-Yuji** [comment]
Working on it
