### ISSUE TITLE
Replace grep inside loop by regex

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#70]
There are many loops with grep operation inside, I noticed that most of them can be replaced by a regex operation inside an 'if' operation (e.g., if [[ SOMETHING =~ REGEX ]]). We should work on this.

**Comment by Pedro84skynet** [comment]
Hi, I'm still in the process of understand the structure of the project, but i want to help on this issue as soon as I'm able.

**Comment by rodrigosiqueira** [comment]
Hi @Pedro84skynet 
This issue is from 2019, and I don't remember the exact context, but I suspect I exaggerated a little bit in the description since I just found grep in a loop in the function `print_files_authors` and `get_available_connectors`. Anyway, If you want, take a look if you can replace those `grep` with a `regex`.

**Comment by Pedro84skynet** [comment]
Ok, and it looks like someone has already worked on those greps. Seems like there's nothing to be done with this issue so ...I'll go to another. thx.
