### ISSUE TITLE
Mail in the kw vars looks weird

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#700]
**Description:**

When I use kw vars, I see:

```
kw Mail configuration variables:
  Local Mail config file: Yes 
  kw mail options: 
    Options to be used when sending a patch (send_opts): --annotate --cover-letter --no-chain-reply-to --thread 
  SSH options: 
    SSH user (ssh_user): root 
    SSH port (ssh_port): 22 
    SSH address (ssh_ip): localhost
```

Notice the ssh option in the mail.

    1. cd to a folder with .kw
    2. kw vars

**Expected behavior:**
Only show kw mail options and also show remote, something like:

```
Local Mail config file: Yes 
  kw mail options: 
    Options to be used when sending a patch (send_opts): --annotate --cover-letter --no-chain-reply-to --thread 
kw remote options:
  Default ssh: 
    SSH user (ssh_user): root 
    SSH port (ssh_port): 22 
    SSH address (ssh_ip): localhost
```

**System information:**
 - OS: Debian Sid
 - kw Version: unstable

**Comment by fernandohjunqueira** [comment]
Me and @GuilhermeMoreno started working on a fix for this issue.

**Comment by rodrigosiqueira** [comment]
@fernandohjunqueira let's drop the `vars` feature since `kw config` is the preferred way of checking variables.
