### ISSUE TITLE
Make kw config show all variables

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#701]
**Description:**

It would be useful if kw config shows all configurations. Something like this:

```
$ kw config
   deploy.reboot yes
   ...
   build.use_llvm yes
   ...
```

**Type:**

Improvement

**Why:**
This will make kw config more friendly

**Comment by davidbtadokoro** [comment]
Hi @rodrigosiqueira
Maybe I'm not understanding the enhancement, but doesn't `kw vars` already does what you are proposing?
Maybe you are referring to show all configuration as, in your example, `build.use_llvm yes` doesn't have a counterpart in `kw vars` output. Nevertheless, if this is the case, shouldn't we make this enhancement in `src/kw_config_loader.sh` (where `kw vars` call is redirected)? Or the redundancy is proposital as to have multiple ways for the user retrieve those infos?

**Comment by rodrigosiqueira** [comment]
I have plans to merge `kw vars` inside `kw config`, but this is a low priority for me right now since I'm busy trying to add all the new features required to complete the beta release.

Anyway, this could be a good quest for you :) Do you want to help with that? Maybe we could have something like:

```
kw config --list
# Just show the raw config options, similar to how git config --list works

kw config --list build
# Only shows build options

kw config --list deploy
# Only shows build options

kw config --list --info
# Show kw vars output

kw config --list build --info
# Show kw build info as the vars show.
```

**Comment by davidbtadokoro** [comment]
I see! Talking to @kwy95 we concluded that maybe that was the purpose. I intend on taking this task,  but maybe not in the nearest future 😅. Either way, thanks for the clarification!
