### ISSUE TITLE
Add support to kw env --destroy

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#703]
Right now, kw env does not support an env destroy feature. We need something like:

```
kw env --destroy SOMETHING [--force]
```

When destroying an env, it is reasonable to expect:

1. Check if the target name matches an env that exists.
2. Completely remove the target env by deleting it. It does not hurt to ask the users if they are sure about that.
3. If the user destroys the current env, kw should be in a state where the current kernel does not have any env.

**Comment by karinesobrinho** [comment]
UFABC team is working on it.

**Comment by rodrigosiqueira** [comment]
@aqu1la are you working in on this issue?

**Comment by aquilamacedo** [comment]
> @aquilamacedo are you working in on this issue?

hi @rodrigosiqueira, yes I am, I'll try to submit the draft of this issue today.
