### ISSUE TITLE
kw remote add fail with namespace

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#714]
**Description:**

kw remote add is not working for non-ip entries.

**How to Reproduce:**

1. Run: `kw remote add ubu-tm root@something`
2. Check: .kw/remote.config
3. You will see something like this:
```
Host ubu-tm                                                                        
  Hostname                                                                         
  Port                                                                             
  User
```

**Expected behavior:**

```
kw remote add ubu-tm root@something
cat .kw/remote.config
Host ubu-tm                                                                        
  Hostname something                                                                   
  Port 22                                                  
  User root
```

**System information:**

- OS: Debian Sid
- kw Version: unstable

**Comment by pomba123** [comment]
Executed the steps, but I had the following output 

![error](https://user-images.githubusercontent.com/16227747/193139931-da34845d-5522-43e7-9fa7-4d9efcfd79c7.png)

Is this the expected output?

**Comment by davidbtadokoro** [comment]
Hi @rodrigosiqueira,
Could not reproduce the error neither. Below is a print of my attempt in a Debian environment:

<img width="1035" alt="Captura de Tela 2022-09-29 às 17 53 00" src="https://user-images.githubusercontent.com/95055784/193140291-21baab2c-9883-464f-9d93-07b6bb85060e.png">

Which commit of the unstable you are?

**Comment by Kamorst** [comment]
Any update? @rodrigosiqueira

**Comment by kwy95** [comment]
Tested on Arch with the latest unstable (8156242) and could not reproduce.

**Comment by karinesobrinho** [comment]
Tested on the last unstable ([https://github.com/kworkflow/kworkflow/commit/954b9119815c21fa8a31daf8a12cb9be2e613851](url) and couldn't  reproduce.
