### ISSUE TITLE
Wrong package dependency for Fedora36

### ISSUE THREAD

**Issue by Kamorst** [kworkflow/kworkflow#715]
**Description:**

On Fedora 36 the installer always asks to install `libguestfs-tools` even the installation process of `./setup.sh -i` is complete successfully.

This happens because libguestfs-tools is not a real package. Upon running `dnf install libguestfs-tools` the real package installed is `virt-win-reg` but on the next time installing **kw** the script don't know that the package which provides `libguestfs-tools` is installed. 

**How to Reproduce:**

1. fresh install Fedora 36
2. run `./setup.sh -i`
3. run `./setup.sh -i` again

**Expected behavior:**

Do not prompt to install not required packages

**Screenshots:**

![image](https://user-images.githubusercontent.com/31375521/192793778-b4b760b9-5cc5-44b3-ab9b-9ccdc4366ecb.png)

**System information:**

 - OS: Fedora 36
 - kw Version: `alpha
Branch: unstable
Commit: e8bd84c`
 - Bash Version: `GNU bash, version 5.1.16(1)-release (x86_64-redhat-linux-gnu)`

**Comment by rodrigosiqueira** [comment]
@mairacanal have you ever seen this issue in your fedora system?

**Comment by mairacanal** [comment]
> @mairacanal have you ever seen this issue in your fedora system?

Yes, but I never had the time for fixing it.

**Comment by rodrigosiqueira** [comment]
> Yes, but I never had the time for fixing it.
I guess it is fixed now :)

https://github.com/kworkflow/kworkflow/pull/719
