### ISSUE TITLE
Remote silent fails to add some specific strings

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#727]
**Description:**

kw has the [remote option](https://kworkflow.org/man/features/remote.html), which is used to set up any target machine connected via the network. Under the hood, it setup a feature that will create a [ssh_config](https://man7.org/linux/man-pages/man5/ssh_config.5.html) file, which kw can reference by using the `-F` option.

This is a new feature, and as a result, it has some bugs. One of them is related to how it parses some of the elements.

**How to Reproduce:**

1. Make sure that you have a `.kw` folder (use [kw init](https://kworkflow.org/man/features/init.html))
2. Try:
```bash
kw remote add something99 root@igt-abc99-0.lala.xpto
```
3. Check the `.kw/remote.config` and notice that `something99` is not inserted.

**Expected behavior:**

The above example shout add:

```
[..]
Host something99
  Hostname igt-abc99-0.lala.xpto
  Port 22
  User root
```

**System information:**

 - OS: Debian Sid
 - kw Version: unstable

**Extra notes**

If you work on this ticket, it is worth checking many other types of strings and adding a proper test for them.

**Comment by WLAraujo** [comment]
Nós da UFABC vamos trabalhar nessa

**Comment by davidbtadokoro** [comment]
@rodrigosiqueira could not reproduce it.
Branch unstable, commit 41341d9

**Comment by aquilamacedo** [comment]
@rodrigosiqueira I tried to reproduce this bug but wasn't able to replicate it.
Branch unstable, commit [cca88c2](https://github.com/kworkflow/kworkflow/commit/cca88c224b59cc8bbca5bc85c8e9dc07c43ca8df)
