### ISSUE TITLE
Remote does not fail when missing parameters

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#728]
**Description:**

kw remote is lacking a proper validation of its parameter.

**How to Reproduce:**

The idea is to add a new remote.

1. Make sure that you have a .kw folder (use [kw init](https://kworkflow.org/man/features/init.html))
2. Try: `kw remote xpto-system root@la-lnx-16`
3. It does not fail

**Expected behavior:**

Since the above command does not have the `add|remove|rename`, it should fail.

**System information:**

- OS: Debian Sid
- kw Version: unstable

**Comment by karinesobrinho** [comment]
UFABC group will provide a solution.
