### ISSUE TITLE
Add an option to display all available remotes

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#729]
**Description:**

Currently, we don't have any mechanism to show all the remotes under kw remote track. It would be nice if we have something like this:

```bash
kw remote --list
  Default: Lala
  Host: Something
   - User
   - IP
   - PORT
  Host: LaLa
   - User
   - IP
   - PORT
```

**Comment by WLAraujo** [comment]
Nós da UFABC vamos trabalhar nessa
