### ISSUE TITLE
Drop support to kw deploy VM

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#735]
kw deploy support QEMU VM via libguestfs. Unfortunately, this feature is not well maintained these days, and I have yet to hear any user that wants to maintain or at least test this feature regularly. Additionally, the remote option can be used with QEMU VM, which makes the support for VM under libguestfs a little bit redundant. To make things worse, maintaining the VM code makes the code hard to read.

Let's drop the VM support. If a brave developer wants to support and maintain this feature one day, I'll be glad to review it, but for now, it is only more work for me.

**Comment by melissawen** [comment]
closed by #738 and #741
