### ISSUE TITLE
Automatically show the current env in the terminal

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#762]
**Description:**

For git users, it is common to set up a function in the `.bashrc` that will append the current branch name if they use `cd` into some specific folder. For example:

```
~/Documents/Repositories/kernels/drm-misc [drm-misc-next]
```
Since kw now provide an env feature, let's find a way to provide a similar feature. Something that would looks like this:

```
~/Documents/Repositories/kernels/drm-misc [drm-misc-next](kw-current_env)
```

We could also expend it to show the default remote:
```
~/Documents/Repositories/kernels/drm-misc [drm-misc-next](current_env:default_remote)
```

**Comment by rodrigosiqueira** [comment]
@aquilamacedo this could be a good issue for you.

**Comment by aquilamacedo** [comment]
Hi @rodrigosiqueira, I'll work on this issue.
