### ISSUE TITLE
kw throws an error message if env.current does not exist when trying to destroy.

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#774]
**Description:**

If you create a new env and right after that try to destroy it, you will see this error:

```bash
kw env --destroy TEST-PT1
Are you sure you want to delete this environment? [y/N]: y
/home/siqueira/.local/lib/kw/kw_env.sh: line 221: /home/siqueira/Documents/Repositories/kernels/amd-next_dal-dev/.kw/env.current: No such file or directory
The "$env_name" environment has been destroyed.
```

I think `kw env --create` is not creating `env.current` after your change.

**How to Reproduce:**

1. Make sure you have a clean setup, without env.
2. Create a new env: kw env --create TEST-PT1
3. Destroy env: kw env --destroy TEST-PT1

I guess we just need a simple check in the kw_env.sh, before the line:

```
current_env=$(< "${local_kw_configs}/${ENV_CURRENT_FILE}")
```

**Expected behavior:**

No error message

**Comment by aquilamacedo** [comment]
I'm working on it.
