### ISSUE TITLE
Make kw work well in the zsh

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#80]
@giulianobelinassi make the kw file work as a driver (See: https://github.com/rodrigosiqueira/kworkflow/commit/649a6141224a06c0db343ca1027bec9ca6bcede3).

It could be nice if we have explicit support zsh :)

@RenatoGeh how about it?

**Comment by rodrigosiqueira** [comment]
@alan-barzilay @kwy95
I suppose we can close this issue, right? If yes, feel free to close it.

**Comment by alan-barzilay** [comment]
Yeah, with tab completion done I can´t think of anything else that is lacking
