### ISSUE TITLE
`kw b --help` shows unrelated warning

### ISSUE THREAD

**Issue by magalilemes** [kworkflow/kworkflow#824]
**Description:**

When running `kw b --help` outside a kernel tree, apart from the manual page, users are also prompted with an unrelated warning.
```
$ kw b --help
Please use kw init to update your config files
```
**How to Reproduce:**

Run `kw b --help` outside a kernel directory.

**Expected behavior:**

Only the man page of kw build should show up.

**System information:**

 - OS: Ubuntu 22.04.2 LTS 
 - kw Version: alpha, Branch: unstable, Commit: edd0f16
 - Bash Version: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

**Comment by GuilhermeMoreno** [comment]
After reviewing the issue, it seems that the offenders are those lines in `build.sh`
```
# Every time build.sh is loaded its proper configuration has to be loaded as well
load_build_config
load_notification_config
```
That is, when `kw` includes `build.sh` it automatically calls these function, without checking whether the user wants to run the build or see the man pages. 

Maybe it would be useful to add a parameter in the `include` function to indicate whether the file is being added as module or main file.
