### ISSUE TITLE
Fix regression introduced by commit #9dd4b81

### ISSUE THREAD

**Issue by davidbtadokoro** [kworkflow/kworkflow#893]
Commit 9dd4b813e5c7a9491c2b735675ae449f0da864e8 introduced a regression in which if we follow the sequence

1. Go to 'Dashboard'->'Bookmarked Patches'
2. Select a bookmarked patchset
3. Hit the return button
4. Go to 'Dashboard'->'Registered Mailing Lists'
5. Select any mailing list
6. See that the feature doesn't fetch new patchsets

A tested draft of fix is in the print below

![Image](https://user-images.githubusercontent.com/95055784/258912875-7a250604-d008-4e23-8eea-db7b6d8106ff.png)

**Comment by jooag** [comment]
Working on it! =)
