### ISSUE TITLE
`kw patch-hub`: Add pagination for 'Registered/Unregistered Mailing Lists' screen

### ISSUE THREAD

**Issue by davidbtadokoro** [kworkflow/kworkflow#901]
**Description:**

The 'Registered/Unregistered Mailing Lists' screen has some missing mailing lists, due to the pagination of lore.kernel.org response. We should add this pagination factor to display all the available mailing lists.

**Type:**

Enhancement.

**Why:**

Although busier lists seem to always be present, we should display all available lore lists.

**Comment by jppaulo06** [comment]
@Andregnl and I will tackle this issue
