### ISSUE TITLE
Unrecognized flag `--eliminate` in fallback command to detect mothboard

### ISSUE THREAD

**Issue by uwla** [kworkflow/kworkflow#924]
**Description:**

Fallback command to detect mothboard uses unrecognized flag.

The fallback command is `cut --eliminate=':' -f2`.

The unrecognize flag is `--eliminate`.

**How to Reproduce:**

1. Spin up a debian VM (see https://flusp.ime.usp.br/kernel/use-qemu-to-play-with-linux/)
2. Install kworkflow in the VM
3. Run `kw device --local`

Last step fails partially:

```
# kw device --local
cut: unrecognized option '--eliminate=:'
Try 'cut --help' for more information.
Chassis:
  Type: Other
CPU:
  Model: QEMU
BIOS
RAM:
  Total RAM: 7.6G
Storage devices:
  Root filesystem: /dev/sda1
  Size: 11G
  Mounted on: /
Operating System:
  Distribution: Debian GNU/Linux
  Distribution version: 12 (bookworm)
  Desktop environments: unidentified
Motherboard:
  Vendor: 
  Name: 
GPU:
  Model: Red Hat, Inc. Device 1100
  Provider: Device 1234:1111 
```

**Expected behavior:**

If the fallback command fails, it should not show error output to the user.
The commands should try to use only POSIX compliant flags.

**Comment by uwla** [comment]
Here is some helpful information about KW and `cut`:

```
# kw --version
alpha
Branch: unstable
Commit: a653137
# cut --version
cut (GNU coreutils) 9.1
```

This outputs belongs to the `VM`.
My host machine has cut version 9.3 and it also does not have the flag `eliminate`.
I don't get the same error in the host machine because the fallback command is not run since the first command succeeds.

**Comment by rodrigosiqueira** [comment]
ohhhh I just realized that we have a typo in the `cut` option. It should be `--delimiter`, not `--eliminate`. @uwla  Could you create a PR fixing that?

**Comment by uwla** [comment]
Sure, I will do that!
