### ISSUE TITLE
Misleading error message when `./setup.sh --install` fails because of unexistent dependency on Arch system

### ISSUE THREAD

**Issue by davidbtadokoro** [kworkflow/kworkflow#949]
**Description:**

Alfter PR #940, recently merged by me, a misleading error message is shown when the dependency that it is trying to be install doesn't exist on an Arch system. The error message is

```
[ERROR]: Dependency installation failure: Lacked sudo privileges to install the packages:
```

even when the user didn't lack sudo privileges.

**How to Reproduce:**

1. Make sure you are on an Arch system
2. Checkout to the unstable branch 
3. Update this branch
4. Add a line to the file `documentation/dependencies/arch.dependencies` like `unexistent-dependency`
5. Run `./setup.sh --install`
6. Say yes to the installation of the dependency and input your admin password

**Expected behavior:**

This misleading error message shouldn't be displayed

**Screenshots:**

Bug in my Arch system

![Screen Shot 2023-11-02 at 02 26 11](https://github.com/kworkflow/kworkflow/assets/95055784/aa07de90-d1a0-4544-889b-d9c61364fe03)

Tested it on a Debian 11 Bullseye, and it doesn't seem to happen

![Screen Shot 2023-11-02 at 02 22 36](https://github.com/kworkflow/kworkflow/assets/95055784/c369cabe-077f-413a-b4e9-25f3593d355e)

**System information:**

 - OS: Manjaro 23.0.4 Uranos
 - kw Version: branch unstable at commit 223d131
 - Bash Version 5.1.16

**Additional Context**

This may be happening on Arch and not Debian, for example, because of the different codes returned by `pacman` and `apt`. The merged PR assumes error code 1 means lack of sudo privileges, which doesn't seem to be true to `pacman`

![Screen Shot 2023-11-02 at 02 42 55](https://github.com/kworkflow/kworkflow/assets/95055784/67227387-152e-4f96-8b69-91e402da4855)

**Comment by davidbtadokoro** [comment]
@uwla and @jppaulo06, sorry for not noticing this "bug" before merging it into the unstable. I only tested it on a Debian 11 VM, and it worked as a charm. My bad, anyway 😞

**Comment by jppaulo06** [comment]
Ohh, I understand. Apparently, pacman returns 1 when the package has not been found...
Maybe, then, we could just print the error given by the package manager. What do you think about it @davidbtadokoro?

**Comment by jppaulo06** [comment]
I did some [changes](https://github.com/GuilhermeMoreno/kworkflow/commit/c3ff87346626c7eb3e3d24732dfeed734d31328e), but didn't like them. It hides the standard output when installing the packages, which makes the problem worse...

Maybe the best way could be to just _complain_ something like "[ERROR]: Dependencies installation has failed.". The user, then, can try to debug it watching the logs given from the package manager.

**Comment by davidbtadokoro** [comment]
Hey @jppaulo06, and thank you so much for addressing this issue!

> Maybe the best way could be to just complain something like "[ERROR]: Dependencies installation has failed.". The user, then, can try to debug it watching the logs given from the package manager.

I kind of agree with this, as the logs given by the package managers are really informative, and a generic, but correct error message is better than a more specific one but misleading 😆.

Looks like the solution provided by [this commit](https://github.com/GuilhermeMoreno/kworkflow/commit/f12b21c91c6c82c56cd4e94c69b071de4c3a4dbd) is a good one. Please, open a PR with it 🙇
