### ISSUE TITLE
Cross-compile option

### ISSUE THREAD

**Issue by rodrigosiqueira** [kworkflow/kworkflow#95]
kw could have support for cross-compilation, we should start by adding arm compilation. We had some legacy code like the one described below that tried to handle this scenario.

```
  if [ $TARGET == "arm" ] ; then
    export ARCH=arm CROSS_COMPILE="ccache arm-linux-gnu-"
  fi
```

**Comment by giulianobelinassi** [comment]
I think this could be generalized easily to any arch. The GNU toolchain usually defines the following name for its binaries:
```
*arch*-*system*-*distributer*-*tool*
```
For instance, for IBM PowerPC machines with Linux and GNU distributer, the GCC driver is called:
```
powerpc-linux-gnu-gcc
```
Or for Intel i686 compatible chips (Pentium Pro) targeting Windows with the MinGW distributer:
```
i686-w64-mingw32-gcc
```
Therefore, it can be implemented just by appending your target arch to `-linux-gnu-gcc`. An easy way to test is to cross compile to your own arch, ie, `x86_64-linux-gnu`.
