### ISSUE TITLE
Add shell bang to shellscripts at src/

### ISSUE THREAD

**Issue by uwla** [kworkflow/kworkflow#998]
**Description:**

Bash scripts at the root of kw and at the `tests` directory have the shellbang `#!/bin/bash`, but those at `src` directory do not have. This makes the source code inconsistent and causes "warnings" in IDEs that have LSP for Bash.

**Type:**

Refactor

**Why:**

1. Make code more consistent.
2. Better development experience for KW developers running IDEs such as LunarVim or Vscodium.

**Comment by rodrigosiqueira** [comment]
Iirc, this was a decision we made many moons ago.

The code under the src/ directory works as a library and is not meant to be executed alone. We expect that other scripts include it, and those scripts should have the bash shebang. For example, kw file is the script that must be executed; the same is true for each test.

Part of this decision was to remove `+x` from any file in the `src` folder.
